import type { ActivityDefinition } from "./types";

const ACTIVITIES_DATA = Object.freeze({
  "act.rem.vector-matrix.vector-ops": {
    "activityId": "act.rem.vector-matrix.vector-ops",
    "activityRevision": "1",
    "moduleId": "rem.vector-matrix",
    "stage": "explanation",
    "objectiveId": "obj.rem.vector-ops",
    "conceptTags": ["rem", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.rem.vector-matrix.vector-ops",
    "contentKey": "content.ko.act.rem.vector-matrix.vector-ops",
    "hintIds": ["hint.act.rem.vector-matrix.vector-ops.1"],
    "misconceptionIds": ["misc.rem.1"],
    "variantPool": ["var.act.rem.vector-matrix.vector-ops.a", "var.act.rem.vector-matrix.vector-ops.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.rem.vector-ops",
      "parityObjectiveId": "obj.rem.vector-ops",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.vector-matrix.vector-ops.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.vector-matrix.vector-ops",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.rem.vector-ops",
      "parityObjectiveId": "obj.rem.vector-ops",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.vector-matrix.vector-ops.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.vector-matrix.vector-ops",
    },
  },
  "act.rem.vector-matrix.dot": {
    "activityId": "act.rem.vector-matrix.dot",
    "activityRevision": "1",
    "moduleId": "rem.vector-matrix",
    "stage": "explanation",
    "objectiveId": "obj.rem.vector-ops",
    "conceptTags": ["rem", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.rem.vector-matrix.dot",
    "contentKey": "content.ko.act.rem.vector-matrix.dot",
    "hintIds": ["hint.act.rem.vector-matrix.dot.1"],
    "misconceptionIds": ["misc.rem.1"],
    "variantPool": ["var.act.rem.vector-matrix.dot.a", "var.act.rem.vector-matrix.dot.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.rem.vector-ops",
      "parityObjectiveId": "obj.rem.vector-ops",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.vector-matrix.dot.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.vector-matrix.dot",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.rem.vector-ops",
      "parityObjectiveId": "obj.rem.vector-ops",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.vector-matrix.dot.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.vector-matrix.dot",
    },
  },
  "act.rem.vector-matrix.matmul": {
    "activityId": "act.rem.vector-matrix.matmul",
    "activityRevision": "1",
    "moduleId": "rem.vector-matrix",
    "stage": "explanation",
    "objectiveId": "obj.rem.vector-ops",
    "conceptTags": ["rem", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.rem.vector-matrix.matmul",
    "contentKey": "content.ko.act.rem.vector-matrix.matmul",
    "hintIds": ["hint.act.rem.vector-matrix.matmul.1"],
    "misconceptionIds": ["misc.rem.1"],
    "variantPool": ["var.act.rem.vector-matrix.matmul.a", "var.act.rem.vector-matrix.matmul.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.rem.vector-ops",
      "parityObjectiveId": "obj.rem.vector-ops",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.vector-matrix.matmul.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.vector-matrix.matmul",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.rem.vector-ops",
      "parityObjectiveId": "obj.rem.vector-ops",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.vector-matrix.matmul.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.vector-matrix.matmul",
    },
  },
  "act.rem.vector-matrix.shape": {
    "activityId": "act.rem.vector-matrix.shape",
    "activityRevision": "1",
    "moduleId": "rem.vector-matrix",
    "stage": "explanation",
    "objectiveId": "obj.rem.vector-ops",
    "conceptTags": ["rem", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.rem.vector-matrix.shape",
    "contentKey": "content.ko.act.rem.vector-matrix.shape",
    "hintIds": ["hint.act.rem.vector-matrix.shape.1"],
    "misconceptionIds": ["misc.rem.1"],
    "variantPool": ["var.act.rem.vector-matrix.shape.a", "var.act.rem.vector-matrix.shape.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.rem.vector-ops",
      "parityObjectiveId": "obj.rem.vector-ops",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.vector-matrix.shape.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.vector-matrix.shape",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.rem.vector-ops",
      "parityObjectiveId": "obj.rem.vector-ops",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.vector-matrix.shape.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.vector-matrix.shape",
    },
  },
  "act.rem.vector-matrix.check": {
    "activityId": "act.rem.vector-matrix.check",
    "activityRevision": "1",
    "moduleId": "rem.vector-matrix",
    "stage": "math",
    "objectiveId": "obj.rem.vector-ops",
    "conceptTags": ["rem", "math"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.rem.vector-matrix.check",
    "contentKey": "content.ko.act.rem.vector-matrix.check",
    "hintIds": ["hint.act.rem.vector-matrix.check.1"],
    "misconceptionIds": ["misc.rem.1"],
    "variantPool": ["var.act.rem.vector-matrix.check.a", "var.act.rem.vector-matrix.check.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "numeric-entry",
      "objectiveId": "obj.rem.vector-ops",
      "parityObjectiveId": "obj.rem.vector-ops",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.rem.vector-matrix.check.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.vector-matrix.check",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "labeled-table",
      "objectiveId": "obj.rem.vector-ops",
      "parityObjectiveId": "obj.rem.vector-ops",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.rem.vector-matrix.check.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.vector-matrix.check",
    },
  },
  "act.rem.probability.discrete": {
    "activityId": "act.rem.probability.discrete",
    "activityRevision": "1",
    "moduleId": "rem.probability",
    "stage": "explanation",
    "objectiveId": "obj.rem.probability-normalize",
    "conceptTags": ["rem", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.rem.probability.discrete",
    "contentKey": "content.ko.act.rem.probability.discrete",
    "hintIds": ["hint.act.rem.probability.discrete.1"],
    "misconceptionIds": ["misc.rem.1"],
    "variantPool": ["var.act.rem.probability.discrete.a", "var.act.rem.probability.discrete.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.rem.probability-normalize",
      "parityObjectiveId": "obj.rem.probability-normalize",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.probability.discrete.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.probability.discrete",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.rem.probability-normalize",
      "parityObjectiveId": "obj.rem.probability-normalize",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.probability.discrete.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.probability.discrete",
    },
  },
  "act.rem.probability.normalize": {
    "activityId": "act.rem.probability.normalize",
    "activityRevision": "1",
    "moduleId": "rem.probability",
    "stage": "explanation",
    "objectiveId": "obj.rem.probability-normalize",
    "conceptTags": ["rem", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.rem.probability.normalize",
    "contentKey": "content.ko.act.rem.probability.normalize",
    "hintIds": ["hint.act.rem.probability.normalize.1"],
    "misconceptionIds": ["misc.rem.1"],
    "variantPool": ["var.act.rem.probability.normalize.a", "var.act.rem.probability.normalize.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.rem.probability-normalize",
      "parityObjectiveId": "obj.rem.probability-normalize",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.probability.normalize.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.probability.normalize",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.rem.probability-normalize",
      "parityObjectiveId": "obj.rem.probability-normalize",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.probability.normalize.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.probability.normalize",
    },
  },
  "act.rem.probability.softmax-prep": {
    "activityId": "act.rem.probability.softmax-prep",
    "activityRevision": "1",
    "moduleId": "rem.probability",
    "stage": "explanation",
    "objectiveId": "obj.rem.probability-normalize",
    "conceptTags": ["rem", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.rem.probability.softmax-prep",
    "contentKey": "content.ko.act.rem.probability.softmax-prep",
    "hintIds": ["hint.act.rem.probability.softmax-prep.1"],
    "misconceptionIds": ["misc.rem.1"],
    "variantPool": ["var.act.rem.probability.softmax-prep.a", "var.act.rem.probability.softmax-prep.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.rem.probability-normalize",
      "parityObjectiveId": "obj.rem.probability-normalize",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.probability.softmax-prep.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.probability.softmax-prep",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.rem.probability-normalize",
      "parityObjectiveId": "obj.rem.probability-normalize",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.probability.softmax-prep.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.probability.softmax-prep",
    },
  },
  "act.rem.probability.check": {
    "activityId": "act.rem.probability.check",
    "activityRevision": "1",
    "moduleId": "rem.probability",
    "stage": "math",
    "objectiveId": "obj.rem.probability-normalize",
    "conceptTags": ["rem", "math"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.rem.probability.check",
    "contentKey": "content.ko.act.rem.probability.check",
    "hintIds": ["hint.act.rem.probability.check.1"],
    "misconceptionIds": ["misc.rem.1"],
    "variantPool": ["var.act.rem.probability.check.a", "var.act.rem.probability.check.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "numeric-entry",
      "objectiveId": "obj.rem.probability-normalize",
      "parityObjectiveId": "obj.rem.probability-normalize",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.rem.probability.check.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.probability.check",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "labeled-table",
      "objectiveId": "obj.rem.probability-normalize",
      "parityObjectiveId": "obj.rem.probability-normalize",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.rem.probability.check.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.probability.check",
    },
  },
  "act.rem.python-numpy.arrays": {
    "activityId": "act.rem.python-numpy.arrays",
    "activityRevision": "1",
    "moduleId": "rem.python-numpy",
    "stage": "explanation",
    "objectiveId": "obj.rem.python-numpy-shape",
    "conceptTags": ["rem", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.rem.python-numpy.arrays",
    "contentKey": "content.ko.act.rem.python-numpy.arrays",
    "hintIds": ["hint.act.rem.python-numpy.arrays.1"],
    "misconceptionIds": ["misc.rem.1"],
    "variantPool": ["var.act.rem.python-numpy.arrays.a", "var.act.rem.python-numpy.arrays.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.rem.python-numpy-shape",
      "parityObjectiveId": "obj.rem.python-numpy-shape",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.python-numpy.arrays.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.python-numpy.arrays",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.rem.python-numpy-shape",
      "parityObjectiveId": "obj.rem.python-numpy-shape",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.python-numpy.arrays.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.python-numpy.arrays",
    },
  },
  "act.rem.python-numpy.shape": {
    "activityId": "act.rem.python-numpy.shape",
    "activityRevision": "1",
    "moduleId": "rem.python-numpy",
    "stage": "explanation",
    "objectiveId": "obj.rem.python-numpy-shape",
    "conceptTags": ["rem", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.rem.python-numpy.shape",
    "contentKey": "content.ko.act.rem.python-numpy.shape",
    "hintIds": ["hint.act.rem.python-numpy.shape.1"],
    "misconceptionIds": ["misc.rem.1"],
    "variantPool": ["var.act.rem.python-numpy.shape.a", "var.act.rem.python-numpy.shape.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.rem.python-numpy-shape",
      "parityObjectiveId": "obj.rem.python-numpy-shape",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.python-numpy.shape.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.python-numpy.shape",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.rem.python-numpy-shape",
      "parityObjectiveId": "obj.rem.python-numpy-shape",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.python-numpy.shape.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.python-numpy.shape",
    },
  },
  "act.rem.python-numpy.ops": {
    "activityId": "act.rem.python-numpy.ops",
    "activityRevision": "1",
    "moduleId": "rem.python-numpy",
    "stage": "explanation",
    "objectiveId": "obj.rem.python-numpy-shape",
    "conceptTags": ["rem", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.rem.python-numpy.ops",
    "contentKey": "content.ko.act.rem.python-numpy.ops",
    "hintIds": ["hint.act.rem.python-numpy.ops.1"],
    "misconceptionIds": ["misc.rem.1"],
    "variantPool": ["var.act.rem.python-numpy.ops.a", "var.act.rem.python-numpy.ops.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.rem.python-numpy-shape",
      "parityObjectiveId": "obj.rem.python-numpy-shape",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.python-numpy.ops.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.python-numpy.ops",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.rem.python-numpy-shape",
      "parityObjectiveId": "obj.rem.python-numpy-shape",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.rem.python-numpy.ops.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.python-numpy.ops",
    },
  },
  "act.rem.python-numpy.check": {
    "activityId": "act.rem.python-numpy.check",
    "activityRevision": "1",
    "moduleId": "rem.python-numpy",
    "stage": "math",
    "objectiveId": "obj.rem.python-numpy-shape",
    "conceptTags": ["rem", "math"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.rem.python-numpy.check",
    "contentKey": "content.ko.act.rem.python-numpy.check",
    "hintIds": ["hint.act.rem.python-numpy.check.1"],
    "misconceptionIds": ["misc.rem.1"],
    "variantPool": ["var.act.rem.python-numpy.check.a", "var.act.rem.python-numpy.check.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "numeric-entry",
      "objectiveId": "obj.rem.python-numpy-shape",
      "parityObjectiveId": "obj.rem.python-numpy-shape",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.rem.python-numpy.check.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.python-numpy.check",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "labeled-table",
      "objectiveId": "obj.rem.python-numpy-shape",
      "parityObjectiveId": "obj.rem.python-numpy-shape",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.rem.python-numpy.check.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.rem.python-numpy.check",
    },
  },
  "act.core.vector-similarity.concept": {
    "activityId": "act.core.vector-similarity.concept",
    "activityRevision": "1",
    "moduleId": "core.vector-similarity",
    "stage": "concept",
    "objectiveId": "obj.core.vector-sim.concept",
    "conceptTags": ["vector-sim", "concept"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.vector-similarity.concept",
    "contentKey": "content.ko.act.core.vector-similarity.concept",
    "hintIds": ["hint.act.core.vector-similarity.concept.1"],
    "misconceptionIds": ["misc.vector-sim.1"],
    "variantPool": ["var.act.core.vector-similarity.concept.a", "var.act.core.vector-similarity.concept.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.core.vector-sim.concept",
      "parityObjectiveId": "obj.core.vector-sim.concept",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.core.vector-similarity.concept.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.vector-similarity.concept",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "multiple-choice",
      "objectiveId": "obj.core.vector-sim.concept",
      "parityObjectiveId": "obj.core.vector-sim.concept",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.core.vector-similarity.concept.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.vector-similarity.concept",
    },
  },
  "act.core.vector-similarity.math": {
    "activityId": "act.core.vector-similarity.math",
    "activityRevision": "1",
    "moduleId": "core.vector-similarity",
    "stage": "math",
    "objectiveId": "obj.core.vector-sim.math",
    "conceptTags": ["vector-sim", "math"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.vector-similarity.math",
    "contentKey": "content.ko.act.core.vector-similarity.math",
    "hintIds": ["hint.act.core.vector-similarity.math.1"],
    "misconceptionIds": ["misc.vector-sim.1"],
    "variantPool": ["var.act.core.vector-similarity.math.a", "var.act.core.vector-similarity.math.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "numeric-entry",
      "objectiveId": "obj.core.vector-sim.math",
      "parityObjectiveId": "obj.core.vector-sim.math",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.core.vector-similarity.math.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.vector-similarity.math",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "labeled-table",
      "objectiveId": "obj.core.vector-sim.math",
      "parityObjectiveId": "obj.core.vector-sim.math",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.core.vector-similarity.math.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.vector-similarity.math",
    },
  },
  "act.core.vector-similarity.impl": {
    "activityId": "act.core.vector-similarity.impl",
    "activityRevision": "1",
    "moduleId": "core.vector-similarity",
    "stage": "implementation",
    "objectiveId": "obj.core.vector-sim.impl",
    "conceptTags": ["vector-sim", "implementation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 12,
    "title": "act.core.vector-similarity.impl",
    "contentKey": "content.ko.act.core.vector-similarity.impl",
    "hintIds": ["hint.act.core.vector-similarity.impl.1"],
    "misconceptionIds": ["misc.vector-sim.1"],
    "variantPool": ["var.act.core.vector-similarity.impl.a", "var.act.core.vector-similarity.impl.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.core.vector-sim.impl",
      "parityObjectiveId": "obj.core.vector-sim.impl",
      "evaluator": {
        "evaluatorId": "implementation.trace-match",
        "evaluatorRevision": "1",
        "params": {
          "expectedStepIds": ["s1", "s2"],
        },
      },
      "fixtureId": "fix.act.core.vector-similarity.impl.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.vector-similarity.impl",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "precomputed-trace",
      "objectiveId": "obj.core.vector-sim.impl",
      "parityObjectiveId": "obj.core.vector-sim.impl",
      "evaluator": {
        "evaluatorId": "implementation.trace-match",
        "evaluatorRevision": "1",
        "params": {
          "expectedStepIds": ["s1", "s2"],
        },
      },
      "fixtureId": "fix.act.core.vector-similarity.impl.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.vector-similarity.impl",
    },
  },
  "act.core.vector-similarity.explain": {
    "activityId": "act.core.vector-similarity.explain",
    "activityRevision": "1",
    "moduleId": "core.vector-similarity",
    "stage": "explanation",
    "objectiveId": "obj.core.vector-sim.concept",
    "conceptTags": ["vector-sim", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.vector-similarity.explain",
    "contentKey": "content.ko.act.core.vector-similarity.explain",
    "hintIds": ["hint.act.core.vector-similarity.explain.1"],
    "misconceptionIds": ["misc.vector-sim.1"],
    "variantPool": ["var.act.core.vector-similarity.explain.a", "var.act.core.vector-similarity.explain.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.core.vector-sim.concept",
      "parityObjectiveId": "obj.core.vector-sim.concept",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.core.vector-similarity.explain.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.vector-similarity.explain",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.core.vector-sim.concept",
      "parityObjectiveId": "obj.core.vector-sim.concept",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.core.vector-similarity.explain.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.vector-similarity.explain",
    },
  },
  "act.core.embedding-position.concept": {
    "activityId": "act.core.embedding-position.concept",
    "activityRevision": "1",
    "moduleId": "core.embedding-position",
    "stage": "concept",
    "objectiveId": "obj.core.embedding-position.concept",
    "conceptTags": ["embedding-position", "concept"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.embedding-position.concept",
    "contentKey": "content.ko.act.core.embedding-position.concept",
    "hintIds": ["hint.act.core.embedding-position.concept.1"],
    "misconceptionIds": ["misc.embedding-position.1"],
    "variantPool": ["var.act.core.embedding-position.concept.a", "var.act.core.embedding-position.concept.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.core.embedding-position.concept",
      "parityObjectiveId": "obj.core.embedding-position.concept",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.core.embedding-position.concept.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.embedding-position.concept",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "multiple-choice",
      "objectiveId": "obj.core.embedding-position.concept",
      "parityObjectiveId": "obj.core.embedding-position.concept",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.core.embedding-position.concept.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.embedding-position.concept",
    },
  },
  "act.core.embedding-position.math": {
    "activityId": "act.core.embedding-position.math",
    "activityRevision": "1",
    "moduleId": "core.embedding-position",
    "stage": "math",
    "objectiveId": "obj.core.embedding-position.math",
    "conceptTags": ["embedding-position", "math"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.embedding-position.math",
    "contentKey": "content.ko.act.core.embedding-position.math",
    "hintIds": ["hint.act.core.embedding-position.math.1"],
    "misconceptionIds": ["misc.embedding-position.1"],
    "variantPool": ["var.act.core.embedding-position.math.a", "var.act.core.embedding-position.math.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "numeric-entry",
      "objectiveId": "obj.core.embedding-position.math",
      "parityObjectiveId": "obj.core.embedding-position.math",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.core.embedding-position.math.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.embedding-position.math",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "labeled-table",
      "objectiveId": "obj.core.embedding-position.math",
      "parityObjectiveId": "obj.core.embedding-position.math",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.core.embedding-position.math.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.embedding-position.math",
    },
  },
  "act.core.embedding-position.impl": {
    "activityId": "act.core.embedding-position.impl",
    "activityRevision": "1",
    "moduleId": "core.embedding-position",
    "stage": "implementation",
    "objectiveId": "obj.core.embedding-position.impl",
    "conceptTags": ["embedding-position", "implementation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 12,
    "title": "act.core.embedding-position.impl",
    "contentKey": "content.ko.act.core.embedding-position.impl",
    "hintIds": ["hint.act.core.embedding-position.impl.1"],
    "misconceptionIds": ["misc.embedding-position.1"],
    "variantPool": ["var.act.core.embedding-position.impl.a", "var.act.core.embedding-position.impl.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.core.embedding-position.impl",
      "parityObjectiveId": "obj.core.embedding-position.impl",
      "evaluator": {
        "evaluatorId": "implementation.trace-match",
        "evaluatorRevision": "1",
        "params": {
          "expectedStepIds": ["s1", "s2"],
        },
      },
      "fixtureId": "fix.act.core.embedding-position.impl.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.embedding-position.impl",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "precomputed-trace",
      "objectiveId": "obj.core.embedding-position.impl",
      "parityObjectiveId": "obj.core.embedding-position.impl",
      "evaluator": {
        "evaluatorId": "implementation.trace-match",
        "evaluatorRevision": "1",
        "params": {
          "expectedStepIds": ["s1", "s2"],
        },
      },
      "fixtureId": "fix.act.core.embedding-position.impl.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.embedding-position.impl",
    },
  },
  "act.core.embedding-position.explain": {
    "activityId": "act.core.embedding-position.explain",
    "activityRevision": "1",
    "moduleId": "core.embedding-position",
    "stage": "explanation",
    "objectiveId": "obj.core.embedding-position.concept",
    "conceptTags": ["embedding-position", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.embedding-position.explain",
    "contentKey": "content.ko.act.core.embedding-position.explain",
    "hintIds": ["hint.act.core.embedding-position.explain.1"],
    "misconceptionIds": ["misc.embedding-position.1"],
    "variantPool": ["var.act.core.embedding-position.explain.a", "var.act.core.embedding-position.explain.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.core.embedding-position.concept",
      "parityObjectiveId": "obj.core.embedding-position.concept",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.core.embedding-position.explain.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.embedding-position.explain",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.core.embedding-position.concept",
      "parityObjectiveId": "obj.core.embedding-position.concept",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.core.embedding-position.explain.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.embedding-position.explain",
    },
  },
  "act.core.sdp.concept": {
    "activityId": "act.core.sdp.concept",
    "activityRevision": "1",
    "moduleId": "core.qkv-scaled-dot-product",
    "stage": "concept",
    "objectiveId": "obj.core.sdp.concept",
    "conceptTags": ["sdp", "concept"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.sdp.concept",
    "contentKey": "content.ko.act.core.sdp.concept",
    "hintIds": ["hint.act.core.sdp.concept.1"],
    "misconceptionIds": ["misc.sdp.1"],
    "variantPool": ["var.act.core.sdp.concept.a", "var.act.core.sdp.concept.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.core.sdp.concept",
      "parityObjectiveId": "obj.core.sdp.concept",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.core.sdp.concept.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.sdp.concept",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "multiple-choice",
      "objectiveId": "obj.core.sdp.concept",
      "parityObjectiveId": "obj.core.sdp.concept",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.core.sdp.concept.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.sdp.concept",
    },
  },
  "act.core.sdp.math": {
    "activityId": "act.core.sdp.math",
    "activityRevision": "1",
    "moduleId": "core.qkv-scaled-dot-product",
    "stage": "math",
    "objectiveId": "obj.core.sdp.math",
    "conceptTags": ["sdp", "math"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.sdp.math",
    "contentKey": "content.ko.act.core.sdp.math",
    "hintIds": ["hint.act.core.sdp.math.1"],
    "misconceptionIds": ["misc.sdp.1"],
    "variantPool": ["var.act.core.sdp.math.a", "var.act.core.sdp.math.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "numeric-entry",
      "objectiveId": "obj.core.sdp.math",
      "parityObjectiveId": "obj.core.sdp.math",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.core.sdp.math.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.sdp.math",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "labeled-table",
      "objectiveId": "obj.core.sdp.math",
      "parityObjectiveId": "obj.core.sdp.math",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.core.sdp.math.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.sdp.math",
    },
  },
  "act.core.sdp.impl": {
    "activityId": "act.core.sdp.impl",
    "activityRevision": "1",
    "moduleId": "core.qkv-scaled-dot-product",
    "stage": "implementation",
    "objectiveId": "obj.core.sdp.impl",
    "conceptTags": ["sdp", "implementation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 12,
    "title": "act.core.sdp.impl",
    "contentKey": "content.ko.act.core.sdp.impl",
    "hintIds": ["hint.act.core.sdp.impl.1"],
    "misconceptionIds": ["misc.sdp.1"],
    "variantPool": ["var.act.core.sdp.impl.a", "var.act.core.sdp.impl.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.core.sdp.impl",
      "parityObjectiveId": "obj.core.sdp.impl",
      "evaluator": {
        "evaluatorId": "implementation.trace-match",
        "evaluatorRevision": "1",
        "params": {
          "expectedStepIds": ["s1", "s2"],
        },
      },
      "fixtureId": "fix.act.core.sdp.impl.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.sdp.impl",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "precomputed-trace",
      "objectiveId": "obj.core.sdp.impl",
      "parityObjectiveId": "obj.core.sdp.impl",
      "evaluator": {
        "evaluatorId": "implementation.trace-match",
        "evaluatorRevision": "1",
        "params": {
          "expectedStepIds": ["s1", "s2"],
        },
      },
      "fixtureId": "fix.act.core.sdp.impl.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.sdp.impl",
    },
  },
  "act.core.sdp.explain": {
    "activityId": "act.core.sdp.explain",
    "activityRevision": "1",
    "moduleId": "core.qkv-scaled-dot-product",
    "stage": "explanation",
    "objectiveId": "obj.core.sdp.concept",
    "conceptTags": ["sdp", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.sdp.explain",
    "contentKey": "content.ko.act.core.sdp.explain",
    "hintIds": ["hint.act.core.sdp.explain.1"],
    "misconceptionIds": ["misc.sdp.1"],
    "variantPool": ["var.act.core.sdp.explain.a", "var.act.core.sdp.explain.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.core.sdp.concept",
      "parityObjectiveId": "obj.core.sdp.concept",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.core.sdp.explain.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.sdp.explain",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.core.sdp.concept",
      "parityObjectiveId": "obj.core.sdp.concept",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.core.sdp.explain.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.sdp.explain",
    },
  },
  "act.core.masking.concept": {
    "activityId": "act.core.masking.concept",
    "activityRevision": "1",
    "moduleId": "core.masking",
    "stage": "concept",
    "objectiveId": "obj.core.masking.concept",
    "conceptTags": ["masking", "concept"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.masking.concept",
    "contentKey": "content.ko.act.core.masking.concept",
    "hintIds": ["hint.act.core.masking.concept.1"],
    "misconceptionIds": ["misc.masking.1"],
    "variantPool": ["var.act.core.masking.concept.a", "var.act.core.masking.concept.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.core.masking.concept",
      "parityObjectiveId": "obj.core.masking.concept",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.core.masking.concept.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.masking.concept",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "multiple-choice",
      "objectiveId": "obj.core.masking.concept",
      "parityObjectiveId": "obj.core.masking.concept",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.core.masking.concept.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.masking.concept",
    },
  },
  "act.core.masking.math": {
    "activityId": "act.core.masking.math",
    "activityRevision": "1",
    "moduleId": "core.masking",
    "stage": "math",
    "objectiveId": "obj.core.masking.math",
    "conceptTags": ["masking", "math"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.masking.math",
    "contentKey": "content.ko.act.core.masking.math",
    "hintIds": ["hint.act.core.masking.math.1"],
    "misconceptionIds": ["misc.masking.1"],
    "variantPool": ["var.act.core.masking.math.a", "var.act.core.masking.math.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "numeric-entry",
      "objectiveId": "obj.core.masking.math",
      "parityObjectiveId": "obj.core.masking.math",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.core.masking.math.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.masking.math",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "labeled-table",
      "objectiveId": "obj.core.masking.math",
      "parityObjectiveId": "obj.core.masking.math",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.core.masking.math.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.masking.math",
    },
  },
  "act.core.masking.impl": {
    "activityId": "act.core.masking.impl",
    "activityRevision": "1",
    "moduleId": "core.masking",
    "stage": "implementation",
    "objectiveId": "obj.core.masking.impl",
    "conceptTags": ["masking", "implementation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 12,
    "title": "act.core.masking.impl",
    "contentKey": "content.ko.act.core.masking.impl",
    "hintIds": ["hint.act.core.masking.impl.1"],
    "misconceptionIds": ["misc.masking.1"],
    "variantPool": ["var.act.core.masking.impl.a", "var.act.core.masking.impl.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.core.masking.impl",
      "parityObjectiveId": "obj.core.masking.impl",
      "evaluator": {
        "evaluatorId": "implementation.trace-match",
        "evaluatorRevision": "1",
        "params": {
          "expectedStepIds": ["s1", "s2"],
        },
      },
      "fixtureId": "fix.act.core.masking.impl.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.masking.impl",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "precomputed-trace",
      "objectiveId": "obj.core.masking.impl",
      "parityObjectiveId": "obj.core.masking.impl",
      "evaluator": {
        "evaluatorId": "implementation.trace-match",
        "evaluatorRevision": "1",
        "params": {
          "expectedStepIds": ["s1", "s2"],
        },
      },
      "fixtureId": "fix.act.core.masking.impl.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.masking.impl",
    },
  },
  "act.core.masking.explain": {
    "activityId": "act.core.masking.explain",
    "activityRevision": "1",
    "moduleId": "core.masking",
    "stage": "explanation",
    "objectiveId": "obj.core.masking.concept",
    "conceptTags": ["masking", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.masking.explain",
    "contentKey": "content.ko.act.core.masking.explain",
    "hintIds": ["hint.act.core.masking.explain.1"],
    "misconceptionIds": ["misc.masking.1"],
    "variantPool": ["var.act.core.masking.explain.a", "var.act.core.masking.explain.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.core.masking.concept",
      "parityObjectiveId": "obj.core.masking.concept",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.core.masking.explain.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.masking.explain",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.core.masking.concept",
      "parityObjectiveId": "obj.core.masking.concept",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.core.masking.explain.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.masking.explain",
    },
  },
  "act.core.multi-head.concept": {
    "activityId": "act.core.multi-head.concept",
    "activityRevision": "1",
    "moduleId": "core.multi-head",
    "stage": "concept",
    "objectiveId": "obj.core.multi-head.concept",
    "conceptTags": ["multi-head", "concept"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.multi-head.concept",
    "contentKey": "content.ko.act.core.multi-head.concept",
    "hintIds": ["hint.act.core.multi-head.concept.1"],
    "misconceptionIds": ["misc.multi-head.1"],
    "variantPool": ["var.act.core.multi-head.concept.a", "var.act.core.multi-head.concept.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.core.multi-head.concept",
      "parityObjectiveId": "obj.core.multi-head.concept",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.core.multi-head.concept.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.multi-head.concept",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "multiple-choice",
      "objectiveId": "obj.core.multi-head.concept",
      "parityObjectiveId": "obj.core.multi-head.concept",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.core.multi-head.concept.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.multi-head.concept",
    },
  },
  "act.core.multi-head.math": {
    "activityId": "act.core.multi-head.math",
    "activityRevision": "1",
    "moduleId": "core.multi-head",
    "stage": "math",
    "objectiveId": "obj.core.multi-head.math",
    "conceptTags": ["multi-head", "math"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.multi-head.math",
    "contentKey": "content.ko.act.core.multi-head.math",
    "hintIds": ["hint.act.core.multi-head.math.1"],
    "misconceptionIds": ["misc.multi-head.1"],
    "variantPool": ["var.act.core.multi-head.math.a", "var.act.core.multi-head.math.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "numeric-entry",
      "objectiveId": "obj.core.multi-head.math",
      "parityObjectiveId": "obj.core.multi-head.math",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.core.multi-head.math.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.multi-head.math",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "labeled-table",
      "objectiveId": "obj.core.multi-head.math",
      "parityObjectiveId": "obj.core.multi-head.math",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.core.multi-head.math.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.multi-head.math",
    },
  },
  "act.core.multi-head.impl": {
    "activityId": "act.core.multi-head.impl",
    "activityRevision": "1",
    "moduleId": "core.multi-head",
    "stage": "implementation",
    "objectiveId": "obj.core.multi-head.impl",
    "conceptTags": ["multi-head", "implementation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 12,
    "title": "act.core.multi-head.impl",
    "contentKey": "content.ko.act.core.multi-head.impl",
    "hintIds": ["hint.act.core.multi-head.impl.1"],
    "misconceptionIds": ["misc.multi-head.1"],
    "variantPool": ["var.act.core.multi-head.impl.a", "var.act.core.multi-head.impl.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.core.multi-head.impl",
      "parityObjectiveId": "obj.core.multi-head.impl",
      "evaluator": {
        "evaluatorId": "implementation.trace-match",
        "evaluatorRevision": "1",
        "params": {
          "expectedStepIds": ["s1", "s2"],
        },
      },
      "fixtureId": "fix.act.core.multi-head.impl.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.multi-head.impl",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "precomputed-trace",
      "objectiveId": "obj.core.multi-head.impl",
      "parityObjectiveId": "obj.core.multi-head.impl",
      "evaluator": {
        "evaluatorId": "implementation.trace-match",
        "evaluatorRevision": "1",
        "params": {
          "expectedStepIds": ["s1", "s2"],
        },
      },
      "fixtureId": "fix.act.core.multi-head.impl.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.multi-head.impl",
    },
  },
  "act.core.multi-head.explain": {
    "activityId": "act.core.multi-head.explain",
    "activityRevision": "1",
    "moduleId": "core.multi-head",
    "stage": "explanation",
    "objectiveId": "obj.core.multi-head.concept",
    "conceptTags": ["multi-head", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.multi-head.explain",
    "contentKey": "content.ko.act.core.multi-head.explain",
    "hintIds": ["hint.act.core.multi-head.explain.1"],
    "misconceptionIds": ["misc.multi-head.1"],
    "variantPool": ["var.act.core.multi-head.explain.a", "var.act.core.multi-head.explain.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.core.multi-head.concept",
      "parityObjectiveId": "obj.core.multi-head.concept",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.core.multi-head.explain.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.multi-head.explain",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.core.multi-head.concept",
      "parityObjectiveId": "obj.core.multi-head.concept",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.core.multi-head.explain.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.multi-head.explain",
    },
  },
  "act.core.residual.concept": {
    "activityId": "act.core.residual.concept",
    "activityRevision": "1",
    "moduleId": "core.residual-layernorm-ffn",
    "stage": "concept",
    "objectiveId": "obj.core.residual.concept",
    "conceptTags": ["residual", "concept"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.residual.concept",
    "contentKey": "content.ko.act.core.residual.concept",
    "hintIds": ["hint.act.core.residual.concept.1"],
    "misconceptionIds": ["misc.residual.1"],
    "variantPool": ["var.act.core.residual.concept.a", "var.act.core.residual.concept.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.core.residual.concept",
      "parityObjectiveId": "obj.core.residual.concept",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.core.residual.concept.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.residual.concept",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "multiple-choice",
      "objectiveId": "obj.core.residual.concept",
      "parityObjectiveId": "obj.core.residual.concept",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.core.residual.concept.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.residual.concept",
    },
  },
  "act.core.residual.math": {
    "activityId": "act.core.residual.math",
    "activityRevision": "1",
    "moduleId": "core.residual-layernorm-ffn",
    "stage": "math",
    "objectiveId": "obj.core.residual.math",
    "conceptTags": ["residual", "math"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.residual.math",
    "contentKey": "content.ko.act.core.residual.math",
    "hintIds": ["hint.act.core.residual.math.1"],
    "misconceptionIds": ["misc.residual.1"],
    "variantPool": ["var.act.core.residual.math.a", "var.act.core.residual.math.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "numeric-entry",
      "objectiveId": "obj.core.residual.math",
      "parityObjectiveId": "obj.core.residual.math",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.core.residual.math.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.residual.math",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "labeled-table",
      "objectiveId": "obj.core.residual.math",
      "parityObjectiveId": "obj.core.residual.math",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.core.residual.math.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.residual.math",
    },
  },
  "act.core.residual.impl": {
    "activityId": "act.core.residual.impl",
    "activityRevision": "1",
    "moduleId": "core.residual-layernorm-ffn",
    "stage": "implementation",
    "objectiveId": "obj.core.residual.impl",
    "conceptTags": ["residual", "implementation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 12,
    "title": "act.core.residual.impl",
    "contentKey": "content.ko.act.core.residual.impl",
    "hintIds": ["hint.act.core.residual.impl.1"],
    "misconceptionIds": ["misc.residual.1"],
    "variantPool": ["var.act.core.residual.impl.a", "var.act.core.residual.impl.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.core.residual.impl",
      "parityObjectiveId": "obj.core.residual.impl",
      "evaluator": {
        "evaluatorId": "implementation.trace-match",
        "evaluatorRevision": "1",
        "params": {
          "expectedStepIds": ["s1", "s2"],
        },
      },
      "fixtureId": "fix.act.core.residual.impl.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.residual.impl",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "precomputed-trace",
      "objectiveId": "obj.core.residual.impl",
      "parityObjectiveId": "obj.core.residual.impl",
      "evaluator": {
        "evaluatorId": "implementation.trace-match",
        "evaluatorRevision": "1",
        "params": {
          "expectedStepIds": ["s1", "s2"],
        },
      },
      "fixtureId": "fix.act.core.residual.impl.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.residual.impl",
    },
  },
  "act.core.residual.explain": {
    "activityId": "act.core.residual.explain",
    "activityRevision": "1",
    "moduleId": "core.residual-layernorm-ffn",
    "stage": "explanation",
    "objectiveId": "obj.core.residual.concept",
    "conceptTags": ["residual", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.residual.explain",
    "contentKey": "content.ko.act.core.residual.explain",
    "hintIds": ["hint.act.core.residual.explain.1"],
    "misconceptionIds": ["misc.residual.1"],
    "variantPool": ["var.act.core.residual.explain.a", "var.act.core.residual.explain.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.core.residual.concept",
      "parityObjectiveId": "obj.core.residual.concept",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.core.residual.explain.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.residual.explain",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.core.residual.concept",
      "parityObjectiveId": "obj.core.residual.concept",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.core.residual.explain.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.residual.explain",
    },
  },
  "act.core.encdec.concept": {
    "activityId": "act.core.encdec.concept",
    "activityRevision": "1",
    "moduleId": "core.encoder-decoder-cross-attention",
    "stage": "concept",
    "objectiveId": "obj.core.encdec.concept",
    "conceptTags": ["encdec", "concept"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.encdec.concept",
    "contentKey": "content.ko.act.core.encdec.concept",
    "hintIds": ["hint.act.core.encdec.concept.1"],
    "misconceptionIds": ["misc.encdec.1"],
    "variantPool": ["var.act.core.encdec.concept.a", "var.act.core.encdec.concept.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.core.encdec.concept",
      "parityObjectiveId": "obj.core.encdec.concept",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.core.encdec.concept.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.encdec.concept",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "multiple-choice",
      "objectiveId": "obj.core.encdec.concept",
      "parityObjectiveId": "obj.core.encdec.concept",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.core.encdec.concept.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.encdec.concept",
    },
  },
  "act.core.encdec.math": {
    "activityId": "act.core.encdec.math",
    "activityRevision": "1",
    "moduleId": "core.encoder-decoder-cross-attention",
    "stage": "math",
    "objectiveId": "obj.core.encdec.math",
    "conceptTags": ["encdec", "math"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.encdec.math",
    "contentKey": "content.ko.act.core.encdec.math",
    "hintIds": ["hint.act.core.encdec.math.1"],
    "misconceptionIds": ["misc.encdec.1"],
    "variantPool": ["var.act.core.encdec.math.a", "var.act.core.encdec.math.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "numeric-entry",
      "objectiveId": "obj.core.encdec.math",
      "parityObjectiveId": "obj.core.encdec.math",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.core.encdec.math.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.encdec.math",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "labeled-table",
      "objectiveId": "obj.core.encdec.math",
      "parityObjectiveId": "obj.core.encdec.math",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.core.encdec.math.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.encdec.math",
    },
  },
  "act.core.encdec.impl": {
    "activityId": "act.core.encdec.impl",
    "activityRevision": "1",
    "moduleId": "core.encoder-decoder-cross-attention",
    "stage": "implementation",
    "objectiveId": "obj.core.encdec.impl",
    "conceptTags": ["encdec", "implementation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 12,
    "title": "act.core.encdec.impl",
    "contentKey": "content.ko.act.core.encdec.impl",
    "hintIds": ["hint.act.core.encdec.impl.1"],
    "misconceptionIds": ["misc.encdec.1"],
    "variantPool": ["var.act.core.encdec.impl.a", "var.act.core.encdec.impl.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.core.encdec.impl",
      "parityObjectiveId": "obj.core.encdec.impl",
      "evaluator": {
        "evaluatorId": "implementation.trace-match",
        "evaluatorRevision": "1",
        "params": {
          "expectedStepIds": ["s1", "s2"],
        },
      },
      "fixtureId": "fix.act.core.encdec.impl.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.encdec.impl",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "precomputed-trace",
      "objectiveId": "obj.core.encdec.impl",
      "parityObjectiveId": "obj.core.encdec.impl",
      "evaluator": {
        "evaluatorId": "implementation.trace-match",
        "evaluatorRevision": "1",
        "params": {
          "expectedStepIds": ["s1", "s2"],
        },
      },
      "fixtureId": "fix.act.core.encdec.impl.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.encdec.impl",
    },
  },
  "act.core.encdec.explain": {
    "activityId": "act.core.encdec.explain",
    "activityRevision": "1",
    "moduleId": "core.encoder-decoder-cross-attention",
    "stage": "explanation",
    "objectiveId": "obj.core.encdec.concept",
    "conceptTags": ["encdec", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.encdec.explain",
    "contentKey": "content.ko.act.core.encdec.explain",
    "hintIds": ["hint.act.core.encdec.explain.1"],
    "misconceptionIds": ["misc.encdec.1"],
    "variantPool": ["var.act.core.encdec.explain.a", "var.act.core.encdec.explain.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.core.encdec.concept",
      "parityObjectiveId": "obj.core.encdec.concept",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.core.encdec.explain.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.encdec.explain",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.core.encdec.concept",
      "parityObjectiveId": "obj.core.encdec.concept",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.core.encdec.explain.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.encdec.explain",
    },
  },
  "act.core.autoregressive.concept": {
    "activityId": "act.core.autoregressive.concept",
    "activityRevision": "1",
    "moduleId": "core.autoregressive-decoding",
    "stage": "concept",
    "objectiveId": "obj.core.autoregressive.concept",
    "conceptTags": ["autoregressive", "concept"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.autoregressive.concept",
    "contentKey": "content.ko.act.core.autoregressive.concept",
    "hintIds": ["hint.act.core.autoregressive.concept.1"],
    "misconceptionIds": ["misc.autoregressive.1"],
    "variantPool": ["var.act.core.autoregressive.concept.a", "var.act.core.autoregressive.concept.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.core.autoregressive.concept",
      "parityObjectiveId": "obj.core.autoregressive.concept",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.core.autoregressive.concept.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.autoregressive.concept",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "multiple-choice",
      "objectiveId": "obj.core.autoregressive.concept",
      "parityObjectiveId": "obj.core.autoregressive.concept",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.core.autoregressive.concept.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.autoregressive.concept",
    },
  },
  "act.core.autoregressive.math": {
    "activityId": "act.core.autoregressive.math",
    "activityRevision": "1",
    "moduleId": "core.autoregressive-decoding",
    "stage": "math",
    "objectiveId": "obj.core.autoregressive.math",
    "conceptTags": ["autoregressive", "math"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.autoregressive.math",
    "contentKey": "content.ko.act.core.autoregressive.math",
    "hintIds": ["hint.act.core.autoregressive.math.1"],
    "misconceptionIds": ["misc.autoregressive.1"],
    "variantPool": ["var.act.core.autoregressive.math.a", "var.act.core.autoregressive.math.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "numeric-entry",
      "objectiveId": "obj.core.autoregressive.math",
      "parityObjectiveId": "obj.core.autoregressive.math",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.core.autoregressive.math.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.autoregressive.math",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "labeled-table",
      "objectiveId": "obj.core.autoregressive.math",
      "parityObjectiveId": "obj.core.autoregressive.math",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.core.autoregressive.math.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.autoregressive.math",
    },
  },
  "act.core.autoregressive.impl": {
    "activityId": "act.core.autoregressive.impl",
    "activityRevision": "1",
    "moduleId": "core.autoregressive-decoding",
    "stage": "implementation",
    "objectiveId": "obj.core.autoregressive.impl",
    "conceptTags": ["autoregressive", "implementation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 12,
    "title": "act.core.autoregressive.impl",
    "contentKey": "content.ko.act.core.autoregressive.impl",
    "hintIds": ["hint.act.core.autoregressive.impl.1"],
    "misconceptionIds": ["misc.autoregressive.1"],
    "variantPool": ["var.act.core.autoregressive.impl.a", "var.act.core.autoregressive.impl.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.core.autoregressive.impl",
      "parityObjectiveId": "obj.core.autoregressive.impl",
      "evaluator": {
        "evaluatorId": "implementation.trace-match",
        "evaluatorRevision": "1",
        "params": {
          "expectedStepIds": ["s1", "s2"],
        },
      },
      "fixtureId": "fix.act.core.autoregressive.impl.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.autoregressive.impl",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "precomputed-trace",
      "objectiveId": "obj.core.autoregressive.impl",
      "parityObjectiveId": "obj.core.autoregressive.impl",
      "evaluator": {
        "evaluatorId": "implementation.trace-match",
        "evaluatorRevision": "1",
        "params": {
          "expectedStepIds": ["s1", "s2"],
        },
      },
      "fixtureId": "fix.act.core.autoregressive.impl.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.autoregressive.impl",
    },
  },
  "act.core.autoregressive.explain": {
    "activityId": "act.core.autoregressive.explain",
    "activityRevision": "1",
    "moduleId": "core.autoregressive-decoding",
    "stage": "explanation",
    "objectiveId": "obj.core.autoregressive.concept",
    "conceptTags": ["autoregressive", "explanation"],
    "required": true,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.core.autoregressive.explain",
    "contentKey": "content.ko.act.core.autoregressive.explain",
    "hintIds": ["hint.act.core.autoregressive.explain.1"],
    "misconceptionIds": ["misc.autoregressive.1"],
    "variantPool": ["var.act.core.autoregressive.explain.a", "var.act.core.autoregressive.explain.b"],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.core.autoregressive.concept",
      "parityObjectiveId": "obj.core.autoregressive.concept",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.core.autoregressive.explain.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.autoregressive.explain",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.core.autoregressive.concept",
      "parityObjectiveId": "obj.core.autoregressive.concept",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.core.autoregressive.explain.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.core.autoregressive.explain",
    },
  },
  "act.deep.training-objective.concept": {
    "activityId": "act.deep.training-objective.concept",
    "activityRevision": "1",
    "moduleId": "deep.training-objective",
    "stage": "concept",
    "objectiveId": "obj.deep.training-objective",
    "conceptTags": ["deep", "concept"],
    "required": false,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.deep.training-objective.concept",
    "contentKey": "content.ko.act.deep.training-objective.concept",
    "hintIds": [],
    "misconceptionIds": [],
    "variantPool": [],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.deep.training-objective",
      "parityObjectiveId": "obj.deep.training-objective",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.deep.training-objective.concept.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.deep.training-objective.concept",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "multiple-choice",
      "objectiveId": "obj.deep.training-objective",
      "parityObjectiveId": "obj.deep.training-objective",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.deep.training-objective.concept.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.deep.training-objective.concept",
    },
  },
  "act.deep.training-objective.check": {
    "activityId": "act.deep.training-objective.check",
    "activityRevision": "1",
    "moduleId": "deep.training-objective",
    "stage": "math",
    "objectiveId": "obj.deep.training-objective",
    "conceptTags": ["deep", "math"],
    "required": false,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.deep.training-objective.check",
    "contentKey": "content.ko.act.deep.training-objective.check",
    "hintIds": [],
    "misconceptionIds": [],
    "variantPool": [],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "numeric-entry",
      "objectiveId": "obj.deep.training-objective",
      "parityObjectiveId": "obj.deep.training-objective",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.deep.training-objective.check.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.deep.training-objective.check",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "labeled-table",
      "objectiveId": "obj.deep.training-objective",
      "parityObjectiveId": "obj.deep.training-objective",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.deep.training-objective.check.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.deep.training-objective.check",
    },
  },
  "act.deep.complexity.concept": {
    "activityId": "act.deep.complexity.concept",
    "activityRevision": "1",
    "moduleId": "deep.computational-complexity",
    "stage": "concept",
    "objectiveId": "obj.deep.complexity",
    "conceptTags": ["deep", "concept"],
    "required": false,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.deep.complexity.concept",
    "contentKey": "content.ko.act.deep.complexity.concept",
    "hintIds": [],
    "misconceptionIds": [],
    "variantPool": [],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.deep.complexity",
      "parityObjectiveId": "obj.deep.complexity",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.deep.complexity.concept.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.deep.complexity.concept",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "multiple-choice",
      "objectiveId": "obj.deep.complexity",
      "parityObjectiveId": "obj.deep.complexity",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.deep.complexity.concept.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.deep.complexity.concept",
    },
  },
  "act.deep.complexity.check": {
    "activityId": "act.deep.complexity.check",
    "activityRevision": "1",
    "moduleId": "deep.computational-complexity",
    "stage": "math",
    "objectiveId": "obj.deep.complexity",
    "conceptTags": ["deep", "math"],
    "required": false,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.deep.complexity.check",
    "contentKey": "content.ko.act.deep.complexity.check",
    "hintIds": [],
    "misconceptionIds": [],
    "variantPool": [],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "numeric-entry",
      "objectiveId": "obj.deep.complexity",
      "parityObjectiveId": "obj.deep.complexity",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.deep.complexity.check.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.deep.complexity.check",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "labeled-table",
      "objectiveId": "obj.deep.complexity",
      "parityObjectiveId": "obj.deep.complexity",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.deep.complexity.check.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.deep.complexity.check",
    },
  },
  "act.deep.experiments.concept": {
    "activityId": "act.deep.experiments.concept",
    "activityRevision": "1",
    "moduleId": "deep.experiment-interpretation",
    "stage": "concept",
    "objectiveId": "obj.deep.experiments",
    "conceptTags": ["deep", "concept"],
    "required": false,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.deep.experiments.concept",
    "contentKey": "content.ko.act.deep.experiments.concept",
    "hintIds": [],
    "misconceptionIds": [],
    "variantPool": [],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "interactive-widget",
      "objectiveId": "obj.deep.experiments",
      "parityObjectiveId": "obj.deep.experiments",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.deep.experiments.concept.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.deep.experiments.concept",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "multiple-choice",
      "objectiveId": "obj.deep.experiments",
      "parityObjectiveId": "obj.deep.experiments",
      "evaluator": {
        "evaluatorId": "concept.multiple-choice",
        "evaluatorRevision": "1",
        "params": {
          "correctOptionIds": ["correct"],
          "requireExactSet": true,
        },
      },
      "fixtureId": "fix.act.deep.experiments.concept.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.deep.experiments.concept",
    },
  },
  "act.deep.experiments.check": {
    "activityId": "act.deep.experiments.check",
    "activityRevision": "1",
    "moduleId": "deep.experiment-interpretation",
    "stage": "math",
    "objectiveId": "obj.deep.experiments",
    "conceptTags": ["deep", "math"],
    "required": false,
    "scorable": true,
    "estimatedMinutes": 10,
    "title": "act.deep.experiments.check",
    "contentKey": "content.ko.act.deep.experiments.check",
    "hintIds": [],
    "misconceptionIds": [],
    "variantPool": [],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "numeric-entry",
      "objectiveId": "obj.deep.experiments",
      "parityObjectiveId": "obj.deep.experiments",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.deep.experiments.check.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.deep.experiments.check",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "labeled-table",
      "objectiveId": "obj.deep.experiments",
      "parityObjectiveId": "obj.deep.experiments",
      "evaluator": {
        "evaluatorId": "concept.exact-numeric",
        "evaluatorRevision": "1",
        "params": {
          "expected": 1,
          "tolerance": 0,
        },
      },
      "fixtureId": "fix.act.deep.experiments.check.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.deep.experiments.check",
    },
  },
  "act.capstone.tiny-transformer.brief": {
    "activityId": "act.capstone.tiny-transformer.brief",
    "activityRevision": "1",
    "moduleId": "capstone.tiny-transformer",
    "stage": "explanation",
    "objectiveId": "obj.capstone.tiny-transformer",
    "conceptTags": ["capstone", "explanation"],
    "required": false,
    "scorable": false,
    "estimatedMinutes": 10,
    "title": "act.capstone.tiny-transformer.brief",
    "contentKey": "content.ko.act.capstone.tiny-transformer.brief",
    "hintIds": [],
    "misconceptionIds": [],
    "variantPool": [],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.capstone.tiny-transformer",
      "parityObjectiveId": "obj.capstone.tiny-transformer",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.capstone.tiny-transformer.brief.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.capstone.tiny-transformer.brief",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.capstone.tiny-transformer",
      "parityObjectiveId": "obj.capstone.tiny-transformer",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.capstone.tiny-transformer.brief.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.capstone.tiny-transformer.brief",
    },
  },
  "act.capstone.architecture.brief": {
    "activityId": "act.capstone.architecture.brief",
    "activityRevision": "1",
    "moduleId": "capstone.architecture-explanation",
    "stage": "explanation",
    "objectiveId": "obj.capstone.architecture",
    "conceptTags": ["capstone", "explanation"],
    "required": false,
    "scorable": false,
    "estimatedMinutes": 10,
    "title": "act.capstone.architecture.brief",
    "contentKey": "content.ko.act.capstone.architecture.brief",
    "hintIds": [],
    "misconceptionIds": [],
    "variantPool": [],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.capstone.architecture",
      "parityObjectiveId": "obj.capstone.architecture",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.capstone.architecture.brief.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.capstone.architecture.brief",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.capstone.architecture",
      "parityObjectiveId": "obj.capstone.architecture",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.capstone.architecture.brief.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.capstone.architecture.brief",
    },
  },
  "act.capstone.paper-critique.brief": {
    "activityId": "act.capstone.paper-critique.brief",
    "activityRevision": "1",
    "moduleId": "capstone.paper-critique",
    "stage": "explanation",
    "objectiveId": "obj.capstone.paper-critique",
    "conceptTags": ["capstone", "explanation"],
    "required": false,
    "scorable": false,
    "estimatedMinutes": 10,
    "title": "act.capstone.paper-critique.brief",
    "contentKey": "content.ko.act.capstone.paper-critique.brief",
    "hintIds": [],
    "misconceptionIds": [],
    "variantPool": [],
    "primaryEvidenceSpec": {
      "mode": "primary",
      "surfaceFormFamily": "structured-rubric",
      "objectiveId": "obj.capstone.paper-critique",
      "parityObjectiveId": "obj.capstone.paper-critique",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.capstone.paper-critique.brief.primary",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.capstone.paper-critique.brief",
    },
    "accessibleEvidenceSpec": {
      "mode": "accessible",
      "surfaceFormFamily": "form-sequence",
      "objectiveId": "obj.capstone.paper-critique",
      "parityObjectiveId": "obj.capstone.paper-critique",
      "evaluator": {
        "evaluatorId": "explanation.structured-rubric",
        "evaluatorRevision": "1",
        "params": {
          "requiredFields": ["claim", "evidence"],
          "minimumNonEmpty": 2,
        },
      },
      "fixtureId": "fix.act.capstone.paper-critique.brief.accessible",
      "fixtureRevision": "1",
      "passPredicateKey": "pass.act.capstone.paper-critique.brief",
    },
  },
});

export const ACTIVITIES: Readonly<Record<string, ActivityDefinition>> = ACTIVITIES_DATA as unknown as Readonly<Record<string, ActivityDefinition>>;

export const ACTIVITY_IDS = Object.freeze(Object.keys(ACTIVITIES) as readonly string[]);
