import type { DiagnosticBank } from "./types";

const mc = {
  evaluatorId: "concept.multiple-choice",
  evaluatorRevision: "1",
  params: { correctOptionIds: ["correct"], requireExactSet: true },
} as const;

function evidence(
  itemId: string,
  objectiveId: string,
  primarySurface: "multiple-choice" | "numeric-entry" | "interactive-widget",
  accessibleSurface: "labeled-table" | "form-sequence" | "multiple-choice",
) {
  const evaluator = { ...mc } as const;
  return {
    primaryEvidenceSpec: {
      mode: "primary" as const,
      surfaceFormFamily: primarySurface,
      objectiveId,
      parityObjectiveId: objectiveId,
      evaluator,
      fixtureId: `fix.${itemId}.primary`,
      fixtureRevision: "1",
      passPredicateKey: `pass.${itemId}`,
    },
    accessibleEvidenceSpec: {
      mode: "accessible" as const,
      surfaceFormFamily: accessibleSurface,
      objectiveId,
      parityObjectiveId: objectiveId,
      evaluator,
      fixtureId: `fix.${itemId}.accessible`,
      fixtureRevision: "1",
      passPredicateKey: `pass.${itemId}`,
    },
  };
}

/** Diagnostic bank: exact 70% ready threshold on required answered items. */
const DIAGNOSTIC_BANK_DATA = {
  bankId: "diagnostic.attention-prep",
  bankRevision: "1",
  readyThresholdPercent: 70,
  domains: ["math", "coding"] as const,
  estimatedMinutes: 25,
  items: [
    {
      itemId: "diag.math.vector-add",
      itemRevision: "1",
      domain: "math",
      conceptTags: ["linear-algebra", "vectors"],
      routeEffect: "ready-signal",
      required: true,
      estimatedMinutes: 3,
      title: "벡터 덧셈",
      objectiveId: "obj.diag.math-linear",
      ...evidence("diag.math.vector-add", "obj.diag.math-linear", "numeric-entry", "labeled-table"),
    },
    {
      itemId: "diag.math.dot-product",
      itemRevision: "1",
      domain: "math",
      conceptTags: ["linear-algebra", "dot-product"],
      routeEffect: "ready-signal",
      required: true,
      estimatedMinutes: 3,
      title: "내적",
      objectiveId: "obj.diag.math-linear",
      ...evidence("diag.math.dot-product", "obj.diag.math-linear", "numeric-entry", "labeled-table"),
    },
    {
      itemId: "diag.math.normalize",
      itemRevision: "1",
      domain: "math",
      conceptTags: ["probability", "normalize"],
      routeEffect: "ready-signal",
      required: true,
      estimatedMinutes: 3,
      title: "점수 정규화",
      objectiveId: "obj.diag.math-prob",
      ...evidence("diag.math.normalize", "obj.diag.math-prob", "multiple-choice", "form-sequence"),
    },
    {
      itemId: "diag.math.softmax-prep",
      itemRevision: "1",
      domain: "math",
      conceptTags: ["probability", "softmax-prep"],
      routeEffect: "ready-signal",
      required: true,
      estimatedMinutes: 3,
      title: "소프트맥스 준비",
      objectiveId: "obj.diag.math-prob",
      ...evidence("diag.math.softmax-prep", "obj.diag.math-prob", "multiple-choice", "labeled-table"),
    },
    {
      itemId: "diag.coding.shape",
      itemRevision: "1",
      domain: "coding",
      conceptTags: ["python", "numpy-shape"],
      routeEffect: "ready-signal",
      required: true,
      estimatedMinutes: 3,
      title: "배열 shape",
      objectiveId: "obj.diag.coding-numpy",
      ...evidence("diag.coding.shape", "obj.diag.coding-numpy", "multiple-choice", "form-sequence"),
    },
    {
      itemId: "diag.coding.broadcast",
      itemRevision: "1",
      domain: "coding",
      conceptTags: ["python", "numpy-shape"],
      routeEffect: "ready-signal",
      required: true,
      estimatedMinutes: 3,
      title: "브로드캐스트 제약",
      objectiveId: "obj.diag.coding-numpy",
      ...evidence("diag.coding.broadcast", "obj.diag.coding-numpy", "interactive-widget", "labeled-table"),
    },
    {
      itemId: "diag.coding.loop",
      itemRevision: "1",
      domain: "coding",
      conceptTags: ["python", "control-flow"],
      routeEffect: "ready-signal",
      required: true,
      estimatedMinutes: 3,
      title: "루프 결과 예측",
      objectiveId: "obj.diag.coding-control",
      ...evidence("diag.coding.loop", "obj.diag.coding-control", "multiple-choice", "form-sequence"),
    },
    {
      itemId: "diag.coding.condition",
      itemRevision: "1",
      domain: "coding",
      conceptTags: ["python", "control-flow"],
      routeEffect: "ready-signal",
      required: true,
      estimatedMinutes: 3,
      title: "조건 분기",
      objectiveId: "obj.diag.coding-control",
      ...evidence("diag.coding.condition", "obj.diag.coding-control", "multiple-choice", "labeled-table"),
    },
    {
      itemId: "diag.math.optional-matrix",
      itemRevision: "1",
      domain: "math",
      conceptTags: ["matrices"],
      routeEffect: "neutral",
      required: false,
      estimatedMinutes: 2,
      title: "선택: 행렬 shape",
      objectiveId: "obj.diag.math-linear",
      ...evidence("diag.math.optional-matrix", "obj.diag.math-linear", "multiple-choice", "labeled-table"),
    },
  ],
} as const satisfies DiagnosticBank;

export const DIAGNOSTIC_BANK: DiagnosticBank = DIAGNOSTIC_BANK_DATA;
