import type { LearningObjective, ModuleDefinition } from "./types";

const GATE_80 = {
  passPercent: 80,
  requireWrongAnswerExplanations: true,
  consecutiveConceptFailuresBeforeRemediation: 2,
} as const;

/** Shared learning objectives referenced by activities and variants. */
export const OBJECTIVES: Readonly<Record<string, LearningObjective>> = Object.freeze({
  "obj.diag.math-linear": {
    objectiveId: "obj.diag.math-linear",
    revision: "1",
    conceptTags: ["linear-algebra", "vectors"],
    title: "진단: 선형대수 기초",
    description: "벡터 연산과 내적 기호를 고교 수준에서 해석한다.",
  },
  "obj.diag.math-prob": {
    objectiveId: "obj.diag.math-prob",
    revision: "1",
    conceptTags: ["probability", "softmax-prep"],
    title: "진단: 확률 기초",
    description: "이산 분포와 정규화 개념을 판별한다.",
  },
  "obj.diag.coding-numpy": {
    objectiveId: "obj.diag.coding-numpy",
    revision: "1",
    conceptTags: ["python", "numpy-shape"],
    title: "진단: 기초 코딩·배열",
    description: "작은 배열 shape와 원소 연산을 판별한다.",
  },
  "obj.diag.coding-control": {
    objectiveId: "obj.diag.coding-control",
    revision: "1",
    conceptTags: ["python", "control-flow"],
    title: "진단: 제어 흐름",
    description: "간단한 루프·조건 결과를 예측한다.",
  },
  "obj.rem.vector-ops": {
    objectiveId: "obj.rem.vector-ops",
    revision: "1",
    conceptTags: ["vectors", "dot-product"],
    title: "벡터 연산과 내적",
    description: "벡터 덧셈·스칼라 곱·내적을 계산하고 해석한다.",
  },
  "obj.rem.matrix-multiply": {
    objectiveId: "obj.rem.matrix-multiply",
    revision: "1",
    conceptTags: ["matrices", "matmul"],
    title: "행렬 곱 shape",
    description: "행렬 곱의 유효 shape와 결과를 판정한다.",
  },
  "obj.rem.probability-normalize": {
    objectiveId: "obj.rem.probability-normalize",
    revision: "1",
    conceptTags: ["probability", "normalize"],
    title: "확률 정규화",
    description: "비음수 점수를 확률 분포로 정규화한다.",
  },
  "obj.rem.python-numpy-shape": {
    objectiveId: "obj.rem.python-numpy-shape",
    revision: "1",
    conceptTags: ["python", "numpy-shape"],
    title: "NumPy shape 읽기",
    description: "작은 배열의 shape와 broadcast 제약을 설명한다.",
  },
  "obj.core.vector-sim.concept": {
    objectiveId: "obj.core.vector-sim.concept",
    revision: "1",
    conceptTags: ["vector-similarity", "dot-product"],
    title: "유사도와 내적 직관",
    description: "벡터 유사도가 attention score의 출발점임을 설명한다.",
  },
  "obj.core.vector-sim.math": {
    objectiveId: "obj.core.vector-sim.math",
    revision: "1",
    conceptTags: ["vector-similarity", "cosine"],
    title: "유사도 계산",
    description: "내적·코사인 유사도를 작은 벡터로 계산한다.",
  },
  "obj.core.vector-sim.impl": {
    objectiveId: "obj.core.vector-sim.impl",
    revision: "1",
    conceptTags: ["vector-similarity", "numpy"],
    title: "유사도 구현 검증",
    description: "결정적 fixture로 유사도 구현 결과를 검증한다.",
  },
  "obj.core.embedding-position.concept": {
    objectiveId: "obj.core.embedding-position.concept",
    revision: "1",
    conceptTags: ["embeddings", "positional-encoding"],
    title: "임베딩과 위치 정보",
    description: "토큰 임베딩과 위치 인코딩의 역할을 구분한다.",
  },
  "obj.core.embedding-position.math": {
    objectiveId: "obj.core.embedding-position.math",
    revision: "1",
    conceptTags: ["positional-encoding", "sinusoid"],
    title: "위치 인코딩 수식",
    description: "사인·코사인 위치 인코딩 항을 계산한다.",
  },
  "obj.core.embedding-position.impl": {
    objectiveId: "obj.core.embedding-position.impl",
    revision: "1",
    conceptTags: ["positional-encoding", "numpy"],
    title: "위치 인코딩 구현",
    description: "작은 시퀀스 위치 인코딩 출력을 검증한다.",
  },
  "obj.core.sdp.concept": {
    objectiveId: "obj.core.sdp.concept",
    revision: "1",
    conceptTags: ["qkv", "scaled-dot-product"],
    title: "Q·K·V와 scaled dot-product",
    description: "query·key·value와 scale 요인을 설명한다.",
  },
  "obj.core.sdp.math": {
    objectiveId: "obj.core.sdp.math",
    revision: "1",
    conceptTags: ["scaled-dot-product", "softmax"],
    title: "Scaled attention 계산",
    description: "QK^T/√d_k 와 softmax 가중치를 계산한다.",
  },
  "obj.core.sdp.impl": {
    objectiveId: "obj.core.sdp.impl",
    revision: "1",
    conceptTags: ["scaled-dot-product", "numpy"],
    title: "Scaled attention 구현",
    description: "작은 행렬로 scaled attention 출력을 검증한다.",
  },
  "obj.core.masking.concept": {
    objectiveId: "obj.core.masking.concept",
    revision: "1",
    conceptTags: ["masking", "causal-mask"],
    title: "마스킹 직관",
    description: "패딩 마스크와 causal 마스크의 목적을 구분한다.",
  },
  "obj.core.masking.math": {
    objectiveId: "obj.core.masking.math",
    revision: "1",
    conceptTags: ["masking", "attention-weights"],
    title: "마스크 적용 계산",
    description: "마스크 후 attention weight가 0이 되는 위치를 판정한다.",
  },
  "obj.core.masking.impl": {
    objectiveId: "obj.core.masking.impl",
    revision: "1",
    conceptTags: ["masking", "numpy"],
    title: "마스크 구현 검증",
    description: "causal mask 적용 결과를 검증한다.",
  },
  "obj.core.multi-head.concept": {
    objectiveId: "obj.core.multi-head.concept",
    revision: "1",
    conceptTags: ["multi-head", "attention"],
    title: "Multi-head 직관",
    description: "여러 head가 서로 다른 부분공간을 본다는 점을 설명한다.",
  },
  "obj.core.multi-head.math": {
    objectiveId: "obj.core.multi-head.math",
    revision: "1",
    conceptTags: ["multi-head", "projection"],
    title: "Head 분할 차원",
    description: "d_model과 head 수에 따른 head 차원을 계산한다.",
  },
  "obj.core.multi-head.impl": {
    objectiveId: "obj.core.multi-head.impl",
    revision: "1",
    conceptTags: ["multi-head", "numpy"],
    title: "Multi-head 결합",
    description: "head concat과 출력 투영 shape을 검증한다.",
  },
  "obj.core.residual.concept": {
    objectiveId: "obj.core.residual.concept",
    revision: "1",
    conceptTags: ["residual", "layer-norm", "ffn"],
    title: "Residual·LN·FFN 역할",
    description: "서브층 주변 residual과 layer norm, FFN의 역할을 설명한다.",
  },
  "obj.core.residual.math": {
    objectiveId: "obj.core.residual.math",
    revision: "1",
    conceptTags: ["layer-norm", "ffn"],
    title: "LN·FFN 차원",
    description: "layer norm과 position-wise FFN의 차원을 계산한다.",
  },
  "obj.core.residual.impl": {
    objectiveId: "obj.core.residual.impl",
    revision: "1",
    conceptTags: ["residual", "numpy"],
    title: "서브층 구현 검증",
    description: "residual add 후 shape 보존을 검증한다.",
  },
  "obj.core.encdec.concept": {
    objectiveId: "obj.core.encdec.concept",
    revision: "1",
    conceptTags: ["encoder", "decoder", "cross-attention"],
    title: "Encoder·Decoder·Cross-attention",
    description: "인코더 출력과 디코더 cross-attention 연결을 설명한다.",
  },
  "obj.core.encdec.math": {
    objectiveId: "obj.core.encdec.math",
    revision: "1",
    conceptTags: ["cross-attention", "shapes"],
    title: "Cross-attention shape",
    description: "decoder Q와 encoder K/V shape 관계를 계산한다.",
  },
  "obj.core.encdec.impl": {
    objectiveId: "obj.core.encdec.impl",
    revision: "1",
    conceptTags: ["cross-attention", "numpy"],
    title: "Cross-attention 구현",
    description: "작은 encoder/decoder fixture로 출력을 검증한다.",
  },
  "obj.core.autoregressive.concept": {
    objectiveId: "obj.core.autoregressive.concept",
    revision: "1",
    conceptTags: ["autoregressive", "decoding"],
    title: "자기회귀 디코딩",
    description: "토큰 단위 생성과 causal 제약을 설명한다.",
  },
  "obj.core.autoregressive.math": {
    objectiveId: "obj.core.autoregressive.math",
    revision: "1",
    conceptTags: ["autoregressive", "logits"],
    title: "디코딩 스텝 계산",
    description: "한 스텝 logits에서 next-token 선택을 판정한다.",
  },
  "obj.core.autoregressive.impl": {
    objectiveId: "obj.core.autoregressive.impl",
    revision: "1",
    conceptTags: ["autoregressive", "numpy"],
    title: "디코딩 트레이스",
    description: "사전 계산 트레이스로 디코딩 순서를 검증한다.",
  },
  "obj.deep.training-objective": {
    objectiveId: "obj.deep.training-objective",
    revision: "1",
    conceptTags: ["training-objective", "label-smoothing"],
    title: "학습 목적함수",
    description: "논문의 학습 목적과 정규화 선택을 해석한다.",
  },
  "obj.deep.complexity": {
    objectiveId: "obj.deep.complexity",
    revision: "1",
    conceptTags: ["complexity", "self-attention"],
    title: "계산 복잡도",
    description: "self-attention 복잡도를 시퀀스 길이 관점에서 비교한다.",
  },
  "obj.deep.experiments": {
    objectiveId: "obj.deep.experiments",
    revision: "1",
    conceptTags: ["experiments", "ablation"],
    title: "실험 해석",
    description: "논문 표의 결과와 한계를 비판적으로 읽는다.",
  },
  "obj.capstone.tiny-transformer": {
    objectiveId: "obj.capstone.tiny-transformer",
    revision: "1",
    conceptTags: ["capstone", "implementation"],
    title: "작은 트랜스포머 구현",
    description: "별도 저장소에서 작은 트랜스포머를 구현·검증한다.",
  },
  "obj.capstone.architecture": {
    objectiveId: "obj.capstone.architecture",
    revision: "1",
    conceptTags: ["capstone", "explanation"],
    title: "전체 구조 설명",
    description: "인코더·디코더 데이터 흐름을 구조적으로 설명한다.",
  },
  "obj.capstone.paper-critique": {
    objectiveId: "obj.capstone.paper-critique",
    revision: "1",
    conceptTags: ["capstone", "critique"],
    title: "논문 설계·실험·한계 비판",
    description: "설계 선택과 실험·한계를 근거 있게 비판한다.",
  },
});

function sessions(
  moduleId: string,
  parts: readonly { id: string; minutes: number; activities: readonly string[] }[],
) {
  return parts.map((part) => ({
    sessionPartId: `${moduleId}.session.${part.id}`,
    estimatedMinutes: part.minutes,
    activityIds: part.activities,
  }));
}

export const MODULES: Readonly<Record<string, ModuleDefinition>> = Object.freeze({
  "rem.vector-matrix": {
    moduleId: "rem.vector-matrix",
    moduleRevision: "1",
    kind: "remedial",
    required: false,
    blocksCoreCompletion: false,
    title: "보충: 벡터·행렬",
    description: "본 경로 진입 전 벡터·행렬 기초를 무전제로 보충한다.",
    englishTerms: ["vector", "matrix", "dot product"],
    sourceCitations: [],
    conceptTags: ["vectors", "matrices", "dot-product"],
    objectiveIds: ["obj.rem.vector-ops", "obj.rem.matrix-multiply"],
    prerequisites: [],
    estimatedMinutes: 180,
    sessionParts: sessions("rem.vector-matrix", [
      {
        id: "a",
        minutes: 40,
        activities: ["act.rem.vector-matrix.vector-ops", "act.rem.vector-matrix.dot"],
      },
      {
        id: "b",
        minutes: 40,
        activities: ["act.rem.vector-matrix.matmul", "act.rem.vector-matrix.shape"],
      },
      {
        id: "c",
        minutes: 35,
        activities: ["act.rem.vector-matrix.check"],
      },
    ]),
    activityIds: ["act.rem.vector-matrix.vector-ops", "act.rem.vector-matrix.dot", "act.rem.vector-matrix.matmul", "act.rem.vector-matrix.shape", "act.rem.vector-matrix.check"],
    masteryGate: GATE_80,
    misconceptionRefs: ["misc.dot-as-elementwise"],
    next: ["core.vector-similarity"],
    contentKey: "content.ko.remedial.vector-matrix",
  },
  "rem.probability": {
    moduleId: "rem.probability",
    moduleRevision: "1",
    kind: "remedial",
    required: false,
    blocksCoreCompletion: false,
    title: "보충: 확률",
    description: "이산 확률과 정규화·softmax 준비를 보충한다.",
    englishTerms: ["probability", "normalize", "softmax"],
    sourceCitations: [],
    conceptTags: ["probability", "normalize"],
    objectiveIds: ["obj.rem.probability-normalize"],
    prerequisites: [],
    estimatedMinutes: 150,
    sessionParts: sessions("rem.probability", [
      {
        id: "a",
        minutes: 40,
        activities: ["act.rem.probability.discrete", "act.rem.probability.normalize"],
      },
      {
        id: "b",
        minutes: 35,
        activities: ["act.rem.probability.softmax-prep", "act.rem.probability.check"],
      },
    ]),
    activityIds: ["act.rem.probability.discrete", "act.rem.probability.normalize", "act.rem.probability.softmax-prep", "act.rem.probability.check"],
    masteryGate: GATE_80,
    misconceptionRefs: ["misc.softmax-without-normalize"],
    next: ["core.qkv-scaled-dot-product"],
    contentKey: "content.ko.remedial.probability",
  },
  "rem.python-numpy": {
    moduleId: "rem.python-numpy",
    moduleRevision: "1",
    kind: "remedial",
    required: false,
    blocksCoreCompletion: false,
    title: "보충: Python·NumPy",
    description: "작은 배열 연산과 shape 읽기 기초를 보충한다.",
    englishTerms: ["Python", "NumPy", "shape"],
    sourceCitations: [],
    conceptTags: ["python", "numpy-shape"],
    objectiveIds: ["obj.rem.python-numpy-shape"],
    prerequisites: [],
    estimatedMinutes: 180,
    sessionParts: sessions("rem.python-numpy", [
      {
        id: "a",
        minutes: 40,
        activities: ["act.rem.python-numpy.arrays", "act.rem.python-numpy.shape"],
      },
      {
        id: "b",
        minutes: 40,
        activities: ["act.rem.python-numpy.ops", "act.rem.python-numpy.check"],
      },
    ]),
    activityIds: ["act.rem.python-numpy.arrays", "act.rem.python-numpy.shape", "act.rem.python-numpy.ops", "act.rem.python-numpy.check"],
    masteryGate: GATE_80,
    misconceptionRefs: ["misc.shape-as-length-only"],
    next: ["core.vector-similarity"],
    contentKey: "content.ko.remedial.python-numpy",
  },
  "core.vector-similarity": {
    moduleId: "core.vector-similarity",
    moduleRevision: "1",
    kind: "core",
    required: true,
    blocksCoreCompletion: true,
    title: "문제 설정과 벡터 유사도",
    description: "어텐션 이전의 유사도 문제와 임베딩 직관을 다룬다.",
    englishTerms: ["embedding", "dot product", "cosine similarity"],
    sourceCitations: ["Vaswani et al., 2017, §3.2.1"],
    conceptTags: ["vector-similarity", "embeddings"],
    objectiveIds: [
      "obj.core.vector-sim.concept",
      "obj.core.vector-sim.math",
      "obj.core.vector-sim.impl",
    ],
    prerequisites: [],
    estimatedMinutes: 135,
    sessionParts: sessions("core.vector-similarity", [
      {
        id: "a",
        minutes: 40,
        activities: [
          "act.core.vector-similarity.concept",
          "act.core.vector-similarity.math",
        ],
      },
      {
        id: "b",
        minutes: 40,
        activities: ["act.core.vector-similarity.impl", "act.core.vector-similarity.explain"],
      },
    ]),
    activityIds: ["act.core.vector-similarity.concept", "act.core.vector-similarity.math", "act.core.vector-similarity.impl", "act.core.vector-similarity.explain"],
    masteryGate: GATE_80,
    misconceptionRefs: ["misc.similarity-requires-unit-norm-only"],
    next: ["core.embedding-position"],
    contentKey: "content.ko.core.vector-similarity",
  },
  "core.embedding-position": {
    moduleId: "core.embedding-position",
    moduleRevision: "1",
    kind: "core",
    required: true,
    blocksCoreCompletion: true,
    title: "임베딩과 위치 인코딩",
    description: "토큰 임베딩과 사인·코사인 위치 인코딩을 연결한다.",
    englishTerms: ["token embedding", "positional encoding"],
    sourceCitations: ["Vaswani et al., 2017, §3.4, §3.5"],
    conceptTags: ["embeddings", "positional-encoding"],
    objectiveIds: [
      "obj.core.embedding-position.concept",
      "obj.core.embedding-position.math",
      "obj.core.embedding-position.impl",
    ],
    prerequisites: ["core.vector-similarity"],
    estimatedMinutes: 150,
    sessionParts: sessions("core.embedding-position", [
      {
        id: "a",
        minutes: 40,
        activities: [
          "act.core.embedding-position.concept",
          "act.core.embedding-position.math",
        ],
      },
      {
        id: "b",
        minutes: 40,
        activities: [
          "act.core.embedding-position.impl",
          "act.core.embedding-position.explain",
        ],
      },
    ]),
    activityIds: ["act.core.embedding-position.concept", "act.core.embedding-position.math", "act.core.embedding-position.impl", "act.core.embedding-position.explain"],
    masteryGate: GATE_80,
    misconceptionRefs: ["misc.position-as-one-hot-only"],
    next: ["core.qkv-scaled-dot-product"],
    contentKey: "content.ko.core.embedding-position",
  },
  "core.qkv-scaled-dot-product": {
    moduleId: "core.qkv-scaled-dot-product",
    moduleRevision: "1",
    kind: "core",
    required: true,
    blocksCoreCompletion: true,
    title: "Q·K·V와 Scaled Dot-Product Attention",
    description: "scaled dot-product attention의 수식과 작은 구현을 익힌다.",
    englishTerms: ["query", "key", "value", "scaled dot-product attention"],
    sourceCitations: ["Vaswani et al., 2017, §3.2.1"],
    conceptTags: ["qkv", "scaled-dot-product"],
    objectiveIds: ["obj.core.sdp.concept", "obj.core.sdp.math", "obj.core.sdp.impl"],
    prerequisites: ["core.embedding-position"],
    estimatedMinutes: 165,
    sessionParts: sessions("core.qkv-scaled-dot-product", [
      {
        id: "a",
        minutes: 45,
        activities: ["act.core.sdp.concept", "act.core.sdp.math"],
      },
      {
        id: "b",
        minutes: 45,
        activities: ["act.core.sdp.impl", "act.core.sdp.explain"],
      },
    ]),
    activityIds: ["act.core.sdp.concept", "act.core.sdp.math", "act.core.sdp.impl", "act.core.sdp.explain"],
    masteryGate: GATE_80,
    misconceptionRefs: ["misc.scale-optional"],
    next: ["core.masking"],
    contentKey: "content.ko.core.qkv-scaled-dot-product",
  },
  "core.masking": {
    moduleId: "core.masking",
    moduleRevision: "1",
    kind: "core",
    required: true,
    blocksCoreCompletion: true,
    title: "어텐션 마스킹",
    description: "패딩 마스크와 causal 마스크가 가중치에 미치는 영향을 다룬다.",
    englishTerms: ["padding mask", "causal mask"],
    sourceCitations: ["Vaswani et al., 2017, §3.2.3"],
    conceptTags: ["masking", "causal-mask"],
    objectiveIds: [
      "obj.core.masking.concept",
      "obj.core.masking.math",
      "obj.core.masking.impl",
    ],
    prerequisites: ["core.qkv-scaled-dot-product"],
    estimatedMinutes: 135,
    sessionParts: sessions("core.masking", [
      {
        id: "a",
        minutes: 40,
        activities: ["act.core.masking.concept", "act.core.masking.math"],
      },
      {
        id: "b",
        minutes: 40,
        activities: ["act.core.masking.impl", "act.core.masking.explain"],
      },
    ]),
    activityIds: ["act.core.masking.concept", "act.core.masking.math", "act.core.masking.impl", "act.core.masking.explain"],
    masteryGate: GATE_80,
    misconceptionRefs: ["misc.mask-after-softmax"],
    next: ["core.multi-head"],
    contentKey: "content.ko.core.masking",
  },
  "core.multi-head": {
    moduleId: "core.multi-head",
    moduleRevision: "1",
    kind: "core",
    required: true,
    blocksCoreCompletion: true,
    title: "Multi-Head Attention",
    description: "여러 head의 부분공간 투영과 결합을 다룬다.",
    englishTerms: ["multi-head attention", "projection"],
    sourceCitations: ["Vaswani et al., 2017, §3.2.2"],
    conceptTags: ["multi-head"],
    objectiveIds: [
      "obj.core.multi-head.concept",
      "obj.core.multi-head.math",
      "obj.core.multi-head.impl",
    ],
    prerequisites: ["core.masking"],
    estimatedMinutes: 150,
    sessionParts: sessions("core.multi-head", [
      {
        id: "a",
        minutes: 40,
        activities: ["act.core.multi-head.concept", "act.core.multi-head.math"],
      },
      {
        id: "b",
        minutes: 40,
        activities: ["act.core.multi-head.impl", "act.core.multi-head.explain"],
      },
    ]),
    activityIds: ["act.core.multi-head.concept", "act.core.multi-head.math", "act.core.multi-head.impl", "act.core.multi-head.explain"],
    masteryGate: GATE_80,
    misconceptionRefs: ["misc.heads-are-ensemble-only"],
    next: ["core.residual-layernorm-ffn"],
    contentKey: "content.ko.core.multi-head",
  },
  "core.residual-layernorm-ffn": {
    moduleId: "core.residual-layernorm-ffn",
    moduleRevision: "1",
    kind: "core",
    required: true,
    blocksCoreCompletion: true,
    title: "Residual, Layer Norm, FFN",
    description: "서브층 주변 연결과 position-wise FFN을 다룬다.",
    englishTerms: ["residual connection", "layer normalization", "feed-forward"],
    sourceCitations: ["Vaswani et al., 2017, §3.1, §3.3"],
    conceptTags: ["residual", "layer-norm", "ffn"],
    objectiveIds: [
      "obj.core.residual.concept",
      "obj.core.residual.math",
      "obj.core.residual.impl",
    ],
    prerequisites: ["core.multi-head"],
    estimatedMinutes: 150,
    sessionParts: sessions("core.residual-layernorm-ffn", [
      {
        id: "a",
        minutes: 40,
        activities: ["act.core.residual.concept", "act.core.residual.math"],
      },
      {
        id: "b",
        minutes: 40,
        activities: ["act.core.residual.impl", "act.core.residual.explain"],
      },
    ]),
    activityIds: ["act.core.residual.concept", "act.core.residual.math", "act.core.residual.impl", "act.core.residual.explain"],
    masteryGate: GATE_80,
    misconceptionRefs: ["misc.ln-after-means-optional"],
    next: ["core.encoder-decoder-cross-attention"],
    contentKey: "content.ko.core.residual-layernorm-ffn",
  },
  "core.encoder-decoder-cross-attention": {
    moduleId: "core.encoder-decoder-cross-attention",
    moduleRevision: "1",
    kind: "core",
    required: true,
    blocksCoreCompletion: true,
    title: "Encoder·Decoder와 Cross-Attention",
    description: "인코더 스택과 디코더 cross-attention 데이터 흐름을 다룬다.",
    englishTerms: ["encoder", "decoder", "cross-attention"],
    sourceCitations: ["Vaswani et al., 2017, §3.1"],
    conceptTags: ["encoder", "decoder", "cross-attention"],
    objectiveIds: [
      "obj.core.encdec.concept",
      "obj.core.encdec.math",
      "obj.core.encdec.impl",
    ],
    prerequisites: ["core.residual-layernorm-ffn"],
    estimatedMinutes: 165,
    sessionParts: sessions("core.encoder-decoder-cross-attention", [
      {
        id: "a",
        minutes: 45,
        activities: ["act.core.encdec.concept", "act.core.encdec.math"],
      },
      {
        id: "b",
        minutes: 45,
        activities: ["act.core.encdec.impl", "act.core.encdec.explain"],
      },
    ]),
    activityIds: ["act.core.encdec.concept", "act.core.encdec.math", "act.core.encdec.impl", "act.core.encdec.explain"],
    masteryGate: GATE_80,
    misconceptionRefs: ["misc.cross-attention-uses-decoder-kv"],
    next: ["core.autoregressive-decoding"],
    contentKey: "content.ko.core.encoder-decoder-cross-attention",
  },
  "core.autoregressive-decoding": {
    moduleId: "core.autoregressive-decoding",
    moduleRevision: "1",
    kind: "core",
    required: true,
    blocksCoreCompletion: true,
    title: "자기회귀 디코딩과 학습 목적 개요",
    description: "토큰 생성 흐름과 학습 목적의 연결, 논문 비판 입문을 다룬다.",
    englishTerms: ["autoregressive decoding", "teacher forcing"],
    sourceCitations: ["Vaswani et al., 2017, §3.1, §5"],
    conceptTags: ["autoregressive", "decoding", "paper-critique"],
    objectiveIds: [
      "obj.core.autoregressive.concept",
      "obj.core.autoregressive.math",
      "obj.core.autoregressive.impl",
    ],
    prerequisites: ["core.encoder-decoder-cross-attention"],
    estimatedMinutes: 165,
    sessionParts: sessions("core.autoregressive-decoding", [
      {
        id: "a",
        minutes: 45,
        activities: ["act.core.autoregressive.concept", "act.core.autoregressive.math"],
      },
      {
        id: "b",
        minutes: 45,
        activities: [
          "act.core.autoregressive.impl",
          "act.core.autoregressive.explain",
        ],
      },
    ]),
    activityIds: ["act.core.autoregressive.concept", "act.core.autoregressive.math", "act.core.autoregressive.impl", "act.core.autoregressive.explain"],
    masteryGate: GATE_80,
    misconceptionRefs: ["misc.decoding-sees-future"],
    next: ["capstone.tiny-transformer"],
    contentKey: "content.ko.core.autoregressive-decoding",
  },
  "deep.training-objective": {
    moduleId: "deep.training-objective",
    moduleRevision: "1",
    kind: "deep-dive",
    required: false,
    blocksCoreCompletion: false,
    title: "심화: 학습 목적함수",
    description: "label smoothing과 학습 스케줄 선택을 선택적으로 깊게 읽는다.",
    englishTerms: ["label smoothing", "learning rate schedule"],
    sourceCitations: ["Vaswani et al., 2017, §5.3, §5.4"],
    conceptTags: ["training-objective"],
    objectiveIds: ["obj.deep.training-objective"],
    prerequisites: ["core.autoregressive-decoding"],
    estimatedMinutes: 90,
    sessionParts: sessions("deep.training-objective", [
      {
        id: "a",
        minutes: 45,
        activities: [
          "act.deep.training-objective.concept",
          "act.deep.training-objective.check",
        ],
      },
    ]),
    activityIds: ["act.deep.training-objective.concept", "act.deep.training-objective.check"],
    masteryGate: null,
    misconceptionRefs: [],
    next: [],
    contentKey: "content.ko.deep-dive.training-objective",
  },
  "deep.computational-complexity": {
    moduleId: "deep.computational-complexity",
    moduleRevision: "1",
    kind: "deep-dive",
    required: false,
    blocksCoreCompletion: false,
    title: "심화: 계산 복잡도",
    description: "self-attention과 순환/합성곱 경로의 복잡도를 비교한다.",
    englishTerms: ["computational complexity", "self-attention"],
    sourceCitations: ["Vaswani et al., 2017, §4, Table 1"],
    conceptTags: ["complexity"],
    objectiveIds: ["obj.deep.complexity"],
    prerequisites: ["core.multi-head"],
    estimatedMinutes: 90,
    sessionParts: sessions("deep.computational-complexity", [
      {
        id: "a",
        minutes: 45,
        activities: ["act.deep.complexity.concept", "act.deep.complexity.check"],
      },
    ]),
    activityIds: ["act.deep.complexity.concept", "act.deep.complexity.check"],
    masteryGate: null,
    misconceptionRefs: [],
    next: [],
    contentKey: "content.ko.deep-dive.computational-complexity",
  },
  "deep.experiment-interpretation": {
    moduleId: "deep.experiment-interpretation",
    moduleRevision: "1",
    kind: "deep-dive",
    required: false,
    blocksCoreCompletion: false,
    title: "심화: 실험 해석",
    description: "논문 실험 표와 ablation을 비판적으로 해석한다.",
    englishTerms: ["ablation", "BLEU", "variation"],
    sourceCitations: ["Vaswani et al., 2017, §6"],
    conceptTags: ["experiments"],
    objectiveIds: ["obj.deep.experiments"],
    prerequisites: ["core.autoregressive-decoding"],
    estimatedMinutes: 90,
    sessionParts: sessions("deep.experiment-interpretation", [
      {
        id: "a",
        minutes: 45,
        activities: ["act.deep.experiments.concept", "act.deep.experiments.check"],
      },
    ]),
    activityIds: ["act.deep.experiments.concept", "act.deep.experiments.check"],
    masteryGate: null,
    misconceptionRefs: [],
    next: [],
    contentKey: "content.ko.deep-dive.experiment-interpretation",
  },
  "capstone.tiny-transformer": {
    moduleId: "capstone.tiny-transformer",
    moduleRevision: "1",
    kind: "capstone",
    required: false,
    blocksCoreCompletion: false,
    title: "캡스톤: 작은 트랜스포머 구현",
    description: "별도 GitHub 저장소에서 작은 트랜스포머 구현 evidence를 제출한다.",
    englishTerms: ["transformer", "repository evidence"],
    sourceCitations: ["Vaswani et al., 2017"],
    conceptTags: ["capstone", "implementation"],
    objectiveIds: ["obj.capstone.tiny-transformer"],
    prerequisites: ["core.autoregressive-decoding"],
    estimatedMinutes: 240,
    sessionParts: sessions("capstone.tiny-transformer", [
      {
        id: "a",
        minutes: 45,
        activities: ["act.capstone.tiny-transformer.brief"],
      },
    ]),
    activityIds: ["act.capstone.tiny-transformer.brief"],
    masteryGate: null,
    misconceptionRefs: [],
    next: ["capstone.architecture-explanation"],
    contentKey: "content.ko.capstone.tiny-transformer",
  },
  "capstone.architecture-explanation": {
    moduleId: "capstone.architecture-explanation",
    moduleRevision: "1",
    kind: "capstone",
    required: false,
    blocksCoreCompletion: false,
    title: "캡스톤: 전체 구조 설명",
    description: "구현에 대응하는 아키텍처 설명을 루브릭으로 자기평가한다.",
    englishTerms: ["architecture explanation"],
    sourceCitations: ["Vaswani et al., 2017, §3"],
    conceptTags: ["capstone", "explanation"],
    objectiveIds: ["obj.capstone.architecture"],
    prerequisites: ["capstone.tiny-transformer"],
    estimatedMinutes: 120,
    sessionParts: sessions("capstone.architecture-explanation", [
      {
        id: "a",
        minutes: 40,
        activities: ["act.capstone.architecture.brief"],
      },
    ]),
    activityIds: ["act.capstone.architecture.brief"],
    masteryGate: null,
    misconceptionRefs: [],
    next: ["capstone.paper-critique"],
    contentKey: "content.ko.capstone.architecture-explanation",
  },
  "capstone.paper-critique": {
    moduleId: "capstone.paper-critique",
    moduleRevision: "1",
    kind: "capstone",
    required: false,
    blocksCoreCompletion: false,
    title: "캡스톤: 논문 비판",
    description: "설계·실험·한계 비판 evidence를 self-assessed/reviewed로 구분한다.",
    englishTerms: ["paper critique", "limitations"],
    sourceCitations: ["Vaswani et al., 2017, §6, §7"],
    conceptTags: ["capstone", "critique"],
    objectiveIds: ["obj.capstone.paper-critique"],
    prerequisites: ["capstone.architecture-explanation"],
    estimatedMinutes: 120,
    sessionParts: sessions("capstone.paper-critique", [
      {
        id: "a",
        minutes: 40,
        activities: ["act.capstone.paper-critique.brief"],
      },
    ]),
    activityIds: ["act.capstone.paper-critique.brief"],
    masteryGate: null,
    misconceptionRefs: [],
    next: [],
    contentKey: "content.ko.capstone.paper-critique",
  },
});

export const CORE_MODULE_IDS = [
  "core.vector-similarity",
  "core.embedding-position",
  "core.qkv-scaled-dot-product",
  "core.masking",
  "core.multi-head",
  "core.residual-layernorm-ffn",
  "core.encoder-decoder-cross-attention",
  "core.autoregressive-decoding",
] as const;

export const DEEP_DIVE_MODULE_IDS = [
  "deep.training-objective",
  "deep.computational-complexity",
  "deep.experiment-interpretation",
] as const;

export const REMEDIAL_MODULE_IDS = [
  "rem.vector-matrix",
  "rem.probability",
  "rem.python-numpy",
] as const;

export const CAPSTONE_MODULE_IDS = [
  "capstone.tiny-transformer",
  "capstone.architecture-explanation",
  "capstone.paper-critique",
] as const;
