import type { VariantDefinition } from "./types";

const VARIANTS_DATA = Object.freeze({
  "var.act.rem.vector-matrix.vector-ops.a": {
    "variantId": "var.act.rem.vector-matrix.vector-ops.a",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.vector-ops",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.vector-matrix.vector-ops",
    "activityId": "act.rem.vector-matrix.vector-ops.variant-a",
    "fixtureId": "fix.act.rem.vector-matrix.vector-ops.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.rem.vector-matrix.vector-ops variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.vector-matrix.vector-ops.variant-a",
  },
  "var.act.rem.vector-matrix.vector-ops.b": {
    "variantId": "var.act.rem.vector-matrix.vector-ops.b",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.vector-ops",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.vector-matrix.vector-ops",
    "activityId": "act.rem.vector-matrix.vector-ops.variant-b",
    "fixtureId": "fix.act.rem.vector-matrix.vector-ops.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.rem.vector-matrix.vector-ops variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.vector-matrix.vector-ops.variant-b",
  },
  "var.act.rem.vector-matrix.dot.a": {
    "variantId": "var.act.rem.vector-matrix.dot.a",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.vector-ops",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.vector-matrix.dot",
    "activityId": "act.rem.vector-matrix.dot.variant-a",
    "fixtureId": "fix.act.rem.vector-matrix.dot.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.rem.vector-matrix.dot variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.vector-matrix.dot.variant-a",
  },
  "var.act.rem.vector-matrix.dot.b": {
    "variantId": "var.act.rem.vector-matrix.dot.b",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.vector-ops",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.vector-matrix.dot",
    "activityId": "act.rem.vector-matrix.dot.variant-b",
    "fixtureId": "fix.act.rem.vector-matrix.dot.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.rem.vector-matrix.dot variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.vector-matrix.dot.variant-b",
  },
  "var.act.rem.vector-matrix.matmul.a": {
    "variantId": "var.act.rem.vector-matrix.matmul.a",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.vector-ops",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.vector-matrix.matmul",
    "activityId": "act.rem.vector-matrix.matmul.variant-a",
    "fixtureId": "fix.act.rem.vector-matrix.matmul.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.rem.vector-matrix.matmul variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.vector-matrix.matmul.variant-a",
  },
  "var.act.rem.vector-matrix.matmul.b": {
    "variantId": "var.act.rem.vector-matrix.matmul.b",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.vector-ops",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.vector-matrix.matmul",
    "activityId": "act.rem.vector-matrix.matmul.variant-b",
    "fixtureId": "fix.act.rem.vector-matrix.matmul.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.rem.vector-matrix.matmul variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.vector-matrix.matmul.variant-b",
  },
  "var.act.rem.vector-matrix.shape.a": {
    "variantId": "var.act.rem.vector-matrix.shape.a",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.vector-ops",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.vector-matrix.shape",
    "activityId": "act.rem.vector-matrix.shape.variant-a",
    "fixtureId": "fix.act.rem.vector-matrix.shape.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.rem.vector-matrix.shape variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.vector-matrix.shape.variant-a",
  },
  "var.act.rem.vector-matrix.shape.b": {
    "variantId": "var.act.rem.vector-matrix.shape.b",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.vector-ops",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.vector-matrix.shape",
    "activityId": "act.rem.vector-matrix.shape.variant-b",
    "fixtureId": "fix.act.rem.vector-matrix.shape.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.rem.vector-matrix.shape variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.vector-matrix.shape.variant-b",
  },
  "var.act.rem.vector-matrix.check.a": {
    "variantId": "var.act.rem.vector-matrix.check.a",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.vector-ops",
    "conceptTags": ["rem", "math"],
    "parentActivityId": "act.rem.vector-matrix.check",
    "activityId": "act.rem.vector-matrix.check.variant-a",
    "fixtureId": "fix.act.rem.vector-matrix.check.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.rem.vector-matrix.check variant a",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.rem.vector-matrix.check.variant-a",
  },
  "var.act.rem.vector-matrix.check.b": {
    "variantId": "var.act.rem.vector-matrix.check.b",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.vector-ops",
    "conceptTags": ["rem", "math"],
    "parentActivityId": "act.rem.vector-matrix.check",
    "activityId": "act.rem.vector-matrix.check.variant-b",
    "fixtureId": "fix.act.rem.vector-matrix.check.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.rem.vector-matrix.check variant b",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.rem.vector-matrix.check.variant-b",
  },
  "var.act.rem.probability.discrete.a": {
    "variantId": "var.act.rem.probability.discrete.a",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.probability-normalize",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.probability.discrete",
    "activityId": "act.rem.probability.discrete.variant-a",
    "fixtureId": "fix.act.rem.probability.discrete.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.rem.probability.discrete variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.probability.discrete.variant-a",
  },
  "var.act.rem.probability.discrete.b": {
    "variantId": "var.act.rem.probability.discrete.b",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.probability-normalize",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.probability.discrete",
    "activityId": "act.rem.probability.discrete.variant-b",
    "fixtureId": "fix.act.rem.probability.discrete.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.rem.probability.discrete variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.probability.discrete.variant-b",
  },
  "var.act.rem.probability.normalize.a": {
    "variantId": "var.act.rem.probability.normalize.a",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.probability-normalize",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.probability.normalize",
    "activityId": "act.rem.probability.normalize.variant-a",
    "fixtureId": "fix.act.rem.probability.normalize.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.rem.probability.normalize variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.probability.normalize.variant-a",
  },
  "var.act.rem.probability.normalize.b": {
    "variantId": "var.act.rem.probability.normalize.b",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.probability-normalize",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.probability.normalize",
    "activityId": "act.rem.probability.normalize.variant-b",
    "fixtureId": "fix.act.rem.probability.normalize.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.rem.probability.normalize variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.probability.normalize.variant-b",
  },
  "var.act.rem.probability.softmax-prep.a": {
    "variantId": "var.act.rem.probability.softmax-prep.a",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.probability-normalize",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.probability.softmax-prep",
    "activityId": "act.rem.probability.softmax-prep.variant-a",
    "fixtureId": "fix.act.rem.probability.softmax-prep.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.rem.probability.softmax-prep variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.probability.softmax-prep.variant-a",
  },
  "var.act.rem.probability.softmax-prep.b": {
    "variantId": "var.act.rem.probability.softmax-prep.b",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.probability-normalize",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.probability.softmax-prep",
    "activityId": "act.rem.probability.softmax-prep.variant-b",
    "fixtureId": "fix.act.rem.probability.softmax-prep.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.rem.probability.softmax-prep variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.probability.softmax-prep.variant-b",
  },
  "var.act.rem.probability.check.a": {
    "variantId": "var.act.rem.probability.check.a",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.probability-normalize",
    "conceptTags": ["rem", "math"],
    "parentActivityId": "act.rem.probability.check",
    "activityId": "act.rem.probability.check.variant-a",
    "fixtureId": "fix.act.rem.probability.check.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.rem.probability.check variant a",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.rem.probability.check.variant-a",
  },
  "var.act.rem.probability.check.b": {
    "variantId": "var.act.rem.probability.check.b",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.probability-normalize",
    "conceptTags": ["rem", "math"],
    "parentActivityId": "act.rem.probability.check",
    "activityId": "act.rem.probability.check.variant-b",
    "fixtureId": "fix.act.rem.probability.check.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.rem.probability.check variant b",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.rem.probability.check.variant-b",
  },
  "var.act.rem.python-numpy.arrays.a": {
    "variantId": "var.act.rem.python-numpy.arrays.a",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.python-numpy-shape",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.python-numpy.arrays",
    "activityId": "act.rem.python-numpy.arrays.variant-a",
    "fixtureId": "fix.act.rem.python-numpy.arrays.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.rem.python-numpy.arrays variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.python-numpy.arrays.variant-a",
  },
  "var.act.rem.python-numpy.arrays.b": {
    "variantId": "var.act.rem.python-numpy.arrays.b",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.python-numpy-shape",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.python-numpy.arrays",
    "activityId": "act.rem.python-numpy.arrays.variant-b",
    "fixtureId": "fix.act.rem.python-numpy.arrays.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.rem.python-numpy.arrays variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.python-numpy.arrays.variant-b",
  },
  "var.act.rem.python-numpy.shape.a": {
    "variantId": "var.act.rem.python-numpy.shape.a",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.python-numpy-shape",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.python-numpy.shape",
    "activityId": "act.rem.python-numpy.shape.variant-a",
    "fixtureId": "fix.act.rem.python-numpy.shape.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.rem.python-numpy.shape variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.python-numpy.shape.variant-a",
  },
  "var.act.rem.python-numpy.shape.b": {
    "variantId": "var.act.rem.python-numpy.shape.b",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.python-numpy-shape",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.python-numpy.shape",
    "activityId": "act.rem.python-numpy.shape.variant-b",
    "fixtureId": "fix.act.rem.python-numpy.shape.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.rem.python-numpy.shape variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.python-numpy.shape.variant-b",
  },
  "var.act.rem.python-numpy.ops.a": {
    "variantId": "var.act.rem.python-numpy.ops.a",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.python-numpy-shape",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.python-numpy.ops",
    "activityId": "act.rem.python-numpy.ops.variant-a",
    "fixtureId": "fix.act.rem.python-numpy.ops.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.rem.python-numpy.ops variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.python-numpy.ops.variant-a",
  },
  "var.act.rem.python-numpy.ops.b": {
    "variantId": "var.act.rem.python-numpy.ops.b",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.python-numpy-shape",
    "conceptTags": ["rem", "explanation"],
    "parentActivityId": "act.rem.python-numpy.ops",
    "activityId": "act.rem.python-numpy.ops.variant-b",
    "fixtureId": "fix.act.rem.python-numpy.ops.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.rem.python-numpy.ops variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.rem.python-numpy.ops.variant-b",
  },
  "var.act.rem.python-numpy.check.a": {
    "variantId": "var.act.rem.python-numpy.check.a",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.python-numpy-shape",
    "conceptTags": ["rem", "math"],
    "parentActivityId": "act.rem.python-numpy.check",
    "activityId": "act.rem.python-numpy.check.variant-a",
    "fixtureId": "fix.act.rem.python-numpy.check.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.rem.python-numpy.check variant a",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.rem.python-numpy.check.variant-a",
  },
  "var.act.rem.python-numpy.check.b": {
    "variantId": "var.act.rem.python-numpy.check.b",
    "variantRevision": "1",
    "conceptFamily": "rem",
    "objectiveId": "obj.rem.python-numpy-shape",
    "conceptTags": ["rem", "math"],
    "parentActivityId": "act.rem.python-numpy.check",
    "activityId": "act.rem.python-numpy.check.variant-b",
    "fixtureId": "fix.act.rem.python-numpy.check.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.rem.python-numpy.check variant b",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.rem.python-numpy.check.variant-b",
  },
  "var.act.core.vector-similarity.concept.a": {
    "variantId": "var.act.core.vector-similarity.concept.a",
    "variantRevision": "1",
    "conceptFamily": "vector-sim",
    "objectiveId": "obj.core.vector-sim.concept",
    "conceptTags": ["vector-sim", "concept"],
    "parentActivityId": "act.core.vector-similarity.concept",
    "activityId": "act.core.vector-similarity.concept.variant-a",
    "fixtureId": "fix.act.core.vector-similarity.concept.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.vector-similarity.concept variant a",
    "evaluator": {
      "evaluatorId": "concept.multiple-choice",
      "evaluatorRevision": "1",
      "params": {
        "correctOptionIds": ["correct"],
        "requireExactSet": true,
      },
    },
    "passPredicateKey": "pass.act.core.vector-similarity.concept.variant-a",
  },
  "var.act.core.vector-similarity.concept.b": {
    "variantId": "var.act.core.vector-similarity.concept.b",
    "variantRevision": "1",
    "conceptFamily": "vector-sim",
    "objectiveId": "obj.core.vector-sim.concept",
    "conceptTags": ["vector-sim", "concept"],
    "parentActivityId": "act.core.vector-similarity.concept",
    "activityId": "act.core.vector-similarity.concept.variant-b",
    "fixtureId": "fix.act.core.vector-similarity.concept.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.vector-similarity.concept variant b",
    "evaluator": {
      "evaluatorId": "concept.multiple-choice",
      "evaluatorRevision": "1",
      "params": {
        "correctOptionIds": ["correct"],
        "requireExactSet": true,
      },
    },
    "passPredicateKey": "pass.act.core.vector-similarity.concept.variant-b",
  },
  "var.act.core.vector-similarity.math.a": {
    "variantId": "var.act.core.vector-similarity.math.a",
    "variantRevision": "1",
    "conceptFamily": "vector-sim",
    "objectiveId": "obj.core.vector-sim.math",
    "conceptTags": ["vector-sim", "math"],
    "parentActivityId": "act.core.vector-similarity.math",
    "activityId": "act.core.vector-similarity.math.variant-a",
    "fixtureId": "fix.act.core.vector-similarity.math.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.vector-similarity.math variant a",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.core.vector-similarity.math.variant-a",
  },
  "var.act.core.vector-similarity.math.b": {
    "variantId": "var.act.core.vector-similarity.math.b",
    "variantRevision": "1",
    "conceptFamily": "vector-sim",
    "objectiveId": "obj.core.vector-sim.math",
    "conceptTags": ["vector-sim", "math"],
    "parentActivityId": "act.core.vector-similarity.math",
    "activityId": "act.core.vector-similarity.math.variant-b",
    "fixtureId": "fix.act.core.vector-similarity.math.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.vector-similarity.math variant b",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.core.vector-similarity.math.variant-b",
  },
  "var.act.core.vector-similarity.impl.a": {
    "variantId": "var.act.core.vector-similarity.impl.a",
    "variantRevision": "1",
    "conceptFamily": "vector-sim",
    "objectiveId": "obj.core.vector-sim.impl",
    "conceptTags": ["vector-sim", "implementation"],
    "parentActivityId": "act.core.vector-similarity.impl",
    "activityId": "act.core.vector-similarity.impl.variant-a",
    "fixtureId": "fix.act.core.vector-similarity.impl.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.vector-similarity.impl variant a",
    "evaluator": {
      "evaluatorId": "implementation.trace-match",
      "evaluatorRevision": "1",
      "params": {
        "expectedStepIds": ["s1", "s2"],
      },
    },
    "passPredicateKey": "pass.act.core.vector-similarity.impl.variant-a",
  },
  "var.act.core.vector-similarity.impl.b": {
    "variantId": "var.act.core.vector-similarity.impl.b",
    "variantRevision": "1",
    "conceptFamily": "vector-sim",
    "objectiveId": "obj.core.vector-sim.impl",
    "conceptTags": ["vector-sim", "implementation"],
    "parentActivityId": "act.core.vector-similarity.impl",
    "activityId": "act.core.vector-similarity.impl.variant-b",
    "fixtureId": "fix.act.core.vector-similarity.impl.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.vector-similarity.impl variant b",
    "evaluator": {
      "evaluatorId": "implementation.trace-match",
      "evaluatorRevision": "1",
      "params": {
        "expectedStepIds": ["s1", "s2"],
      },
    },
    "passPredicateKey": "pass.act.core.vector-similarity.impl.variant-b",
  },
  "var.act.core.vector-similarity.explain.a": {
    "variantId": "var.act.core.vector-similarity.explain.a",
    "variantRevision": "1",
    "conceptFamily": "vector-sim",
    "objectiveId": "obj.core.vector-sim.concept",
    "conceptTags": ["vector-sim", "explanation"],
    "parentActivityId": "act.core.vector-similarity.explain",
    "activityId": "act.core.vector-similarity.explain.variant-a",
    "fixtureId": "fix.act.core.vector-similarity.explain.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.core.vector-similarity.explain variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.core.vector-similarity.explain.variant-a",
  },
  "var.act.core.vector-similarity.explain.b": {
    "variantId": "var.act.core.vector-similarity.explain.b",
    "variantRevision": "1",
    "conceptFamily": "vector-sim",
    "objectiveId": "obj.core.vector-sim.concept",
    "conceptTags": ["vector-sim", "explanation"],
    "parentActivityId": "act.core.vector-similarity.explain",
    "activityId": "act.core.vector-similarity.explain.variant-b",
    "fixtureId": "fix.act.core.vector-similarity.explain.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.vector-similarity.explain variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.core.vector-similarity.explain.variant-b",
  },
  "var.act.core.embedding-position.concept.a": {
    "variantId": "var.act.core.embedding-position.concept.a",
    "variantRevision": "1",
    "conceptFamily": "embedding-position",
    "objectiveId": "obj.core.embedding-position.concept",
    "conceptTags": ["embedding-position", "concept"],
    "parentActivityId": "act.core.embedding-position.concept",
    "activityId": "act.core.embedding-position.concept.variant-a",
    "fixtureId": "fix.act.core.embedding-position.concept.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.embedding-position.concept variant a",
    "evaluator": {
      "evaluatorId": "concept.multiple-choice",
      "evaluatorRevision": "1",
      "params": {
        "correctOptionIds": ["correct"],
        "requireExactSet": true,
      },
    },
    "passPredicateKey": "pass.act.core.embedding-position.concept.variant-a",
  },
  "var.act.core.embedding-position.concept.b": {
    "variantId": "var.act.core.embedding-position.concept.b",
    "variantRevision": "1",
    "conceptFamily": "embedding-position",
    "objectiveId": "obj.core.embedding-position.concept",
    "conceptTags": ["embedding-position", "concept"],
    "parentActivityId": "act.core.embedding-position.concept",
    "activityId": "act.core.embedding-position.concept.variant-b",
    "fixtureId": "fix.act.core.embedding-position.concept.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.embedding-position.concept variant b",
    "evaluator": {
      "evaluatorId": "concept.multiple-choice",
      "evaluatorRevision": "1",
      "params": {
        "correctOptionIds": ["correct"],
        "requireExactSet": true,
      },
    },
    "passPredicateKey": "pass.act.core.embedding-position.concept.variant-b",
  },
  "var.act.core.embedding-position.math.a": {
    "variantId": "var.act.core.embedding-position.math.a",
    "variantRevision": "1",
    "conceptFamily": "embedding-position",
    "objectiveId": "obj.core.embedding-position.math",
    "conceptTags": ["embedding-position", "math"],
    "parentActivityId": "act.core.embedding-position.math",
    "activityId": "act.core.embedding-position.math.variant-a",
    "fixtureId": "fix.act.core.embedding-position.math.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.embedding-position.math variant a",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.core.embedding-position.math.variant-a",
  },
  "var.act.core.embedding-position.math.b": {
    "variantId": "var.act.core.embedding-position.math.b",
    "variantRevision": "1",
    "conceptFamily": "embedding-position",
    "objectiveId": "obj.core.embedding-position.math",
    "conceptTags": ["embedding-position", "math"],
    "parentActivityId": "act.core.embedding-position.math",
    "activityId": "act.core.embedding-position.math.variant-b",
    "fixtureId": "fix.act.core.embedding-position.math.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.embedding-position.math variant b",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.core.embedding-position.math.variant-b",
  },
  "var.act.core.embedding-position.impl.a": {
    "variantId": "var.act.core.embedding-position.impl.a",
    "variantRevision": "1",
    "conceptFamily": "embedding-position",
    "objectiveId": "obj.core.embedding-position.impl",
    "conceptTags": ["embedding-position", "implementation"],
    "parentActivityId": "act.core.embedding-position.impl",
    "activityId": "act.core.embedding-position.impl.variant-a",
    "fixtureId": "fix.act.core.embedding-position.impl.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.embedding-position.impl variant a",
    "evaluator": {
      "evaluatorId": "implementation.trace-match",
      "evaluatorRevision": "1",
      "params": {
        "expectedStepIds": ["s1", "s2"],
      },
    },
    "passPredicateKey": "pass.act.core.embedding-position.impl.variant-a",
  },
  "var.act.core.embedding-position.impl.b": {
    "variantId": "var.act.core.embedding-position.impl.b",
    "variantRevision": "1",
    "conceptFamily": "embedding-position",
    "objectiveId": "obj.core.embedding-position.impl",
    "conceptTags": ["embedding-position", "implementation"],
    "parentActivityId": "act.core.embedding-position.impl",
    "activityId": "act.core.embedding-position.impl.variant-b",
    "fixtureId": "fix.act.core.embedding-position.impl.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.embedding-position.impl variant b",
    "evaluator": {
      "evaluatorId": "implementation.trace-match",
      "evaluatorRevision": "1",
      "params": {
        "expectedStepIds": ["s1", "s2"],
      },
    },
    "passPredicateKey": "pass.act.core.embedding-position.impl.variant-b",
  },
  "var.act.core.embedding-position.explain.a": {
    "variantId": "var.act.core.embedding-position.explain.a",
    "variantRevision": "1",
    "conceptFamily": "embedding-position",
    "objectiveId": "obj.core.embedding-position.concept",
    "conceptTags": ["embedding-position", "explanation"],
    "parentActivityId": "act.core.embedding-position.explain",
    "activityId": "act.core.embedding-position.explain.variant-a",
    "fixtureId": "fix.act.core.embedding-position.explain.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.core.embedding-position.explain variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.core.embedding-position.explain.variant-a",
  },
  "var.act.core.embedding-position.explain.b": {
    "variantId": "var.act.core.embedding-position.explain.b",
    "variantRevision": "1",
    "conceptFamily": "embedding-position",
    "objectiveId": "obj.core.embedding-position.concept",
    "conceptTags": ["embedding-position", "explanation"],
    "parentActivityId": "act.core.embedding-position.explain",
    "activityId": "act.core.embedding-position.explain.variant-b",
    "fixtureId": "fix.act.core.embedding-position.explain.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.embedding-position.explain variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.core.embedding-position.explain.variant-b",
  },
  "var.act.core.sdp.concept.a": {
    "variantId": "var.act.core.sdp.concept.a",
    "variantRevision": "1",
    "conceptFamily": "sdp",
    "objectiveId": "obj.core.sdp.concept",
    "conceptTags": ["sdp", "concept"],
    "parentActivityId": "act.core.sdp.concept",
    "activityId": "act.core.sdp.concept.variant-a",
    "fixtureId": "fix.act.core.sdp.concept.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.sdp.concept variant a",
    "evaluator": {
      "evaluatorId": "concept.multiple-choice",
      "evaluatorRevision": "1",
      "params": {
        "correctOptionIds": ["correct"],
        "requireExactSet": true,
      },
    },
    "passPredicateKey": "pass.act.core.sdp.concept.variant-a",
  },
  "var.act.core.sdp.concept.b": {
    "variantId": "var.act.core.sdp.concept.b",
    "variantRevision": "1",
    "conceptFamily": "sdp",
    "objectiveId": "obj.core.sdp.concept",
    "conceptTags": ["sdp", "concept"],
    "parentActivityId": "act.core.sdp.concept",
    "activityId": "act.core.sdp.concept.variant-b",
    "fixtureId": "fix.act.core.sdp.concept.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.sdp.concept variant b",
    "evaluator": {
      "evaluatorId": "concept.multiple-choice",
      "evaluatorRevision": "1",
      "params": {
        "correctOptionIds": ["correct"],
        "requireExactSet": true,
      },
    },
    "passPredicateKey": "pass.act.core.sdp.concept.variant-b",
  },
  "var.act.core.sdp.math.a": {
    "variantId": "var.act.core.sdp.math.a",
    "variantRevision": "1",
    "conceptFamily": "sdp",
    "objectiveId": "obj.core.sdp.math",
    "conceptTags": ["sdp", "math"],
    "parentActivityId": "act.core.sdp.math",
    "activityId": "act.core.sdp.math.variant-a",
    "fixtureId": "fix.act.core.sdp.math.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.sdp.math variant a",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.core.sdp.math.variant-a",
  },
  "var.act.core.sdp.math.b": {
    "variantId": "var.act.core.sdp.math.b",
    "variantRevision": "1",
    "conceptFamily": "sdp",
    "objectiveId": "obj.core.sdp.math",
    "conceptTags": ["sdp", "math"],
    "parentActivityId": "act.core.sdp.math",
    "activityId": "act.core.sdp.math.variant-b",
    "fixtureId": "fix.act.core.sdp.math.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.sdp.math variant b",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.core.sdp.math.variant-b",
  },
  "var.act.core.sdp.impl.a": {
    "variantId": "var.act.core.sdp.impl.a",
    "variantRevision": "1",
    "conceptFamily": "sdp",
    "objectiveId": "obj.core.sdp.impl",
    "conceptTags": ["sdp", "implementation"],
    "parentActivityId": "act.core.sdp.impl",
    "activityId": "act.core.sdp.impl.variant-a",
    "fixtureId": "fix.act.core.sdp.impl.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.sdp.impl variant a",
    "evaluator": {
      "evaluatorId": "implementation.trace-match",
      "evaluatorRevision": "1",
      "params": {
        "expectedStepIds": ["s1", "s2"],
      },
    },
    "passPredicateKey": "pass.act.core.sdp.impl.variant-a",
  },
  "var.act.core.sdp.impl.b": {
    "variantId": "var.act.core.sdp.impl.b",
    "variantRevision": "1",
    "conceptFamily": "sdp",
    "objectiveId": "obj.core.sdp.impl",
    "conceptTags": ["sdp", "implementation"],
    "parentActivityId": "act.core.sdp.impl",
    "activityId": "act.core.sdp.impl.variant-b",
    "fixtureId": "fix.act.core.sdp.impl.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.sdp.impl variant b",
    "evaluator": {
      "evaluatorId": "implementation.trace-match",
      "evaluatorRevision": "1",
      "params": {
        "expectedStepIds": ["s1", "s2"],
      },
    },
    "passPredicateKey": "pass.act.core.sdp.impl.variant-b",
  },
  "var.act.core.sdp.explain.a": {
    "variantId": "var.act.core.sdp.explain.a",
    "variantRevision": "1",
    "conceptFamily": "sdp",
    "objectiveId": "obj.core.sdp.concept",
    "conceptTags": ["sdp", "explanation"],
    "parentActivityId": "act.core.sdp.explain",
    "activityId": "act.core.sdp.explain.variant-a",
    "fixtureId": "fix.act.core.sdp.explain.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.core.sdp.explain variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.core.sdp.explain.variant-a",
  },
  "var.act.core.sdp.explain.b": {
    "variantId": "var.act.core.sdp.explain.b",
    "variantRevision": "1",
    "conceptFamily": "sdp",
    "objectiveId": "obj.core.sdp.concept",
    "conceptTags": ["sdp", "explanation"],
    "parentActivityId": "act.core.sdp.explain",
    "activityId": "act.core.sdp.explain.variant-b",
    "fixtureId": "fix.act.core.sdp.explain.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.sdp.explain variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.core.sdp.explain.variant-b",
  },
  "var.act.core.masking.concept.a": {
    "variantId": "var.act.core.masking.concept.a",
    "variantRevision": "1",
    "conceptFamily": "masking",
    "objectiveId": "obj.core.masking.concept",
    "conceptTags": ["masking", "concept"],
    "parentActivityId": "act.core.masking.concept",
    "activityId": "act.core.masking.concept.variant-a",
    "fixtureId": "fix.act.core.masking.concept.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.masking.concept variant a",
    "evaluator": {
      "evaluatorId": "concept.multiple-choice",
      "evaluatorRevision": "1",
      "params": {
        "correctOptionIds": ["correct"],
        "requireExactSet": true,
      },
    },
    "passPredicateKey": "pass.act.core.masking.concept.variant-a",
  },
  "var.act.core.masking.concept.b": {
    "variantId": "var.act.core.masking.concept.b",
    "variantRevision": "1",
    "conceptFamily": "masking",
    "objectiveId": "obj.core.masking.concept",
    "conceptTags": ["masking", "concept"],
    "parentActivityId": "act.core.masking.concept",
    "activityId": "act.core.masking.concept.variant-b",
    "fixtureId": "fix.act.core.masking.concept.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.masking.concept variant b",
    "evaluator": {
      "evaluatorId": "concept.multiple-choice",
      "evaluatorRevision": "1",
      "params": {
        "correctOptionIds": ["correct"],
        "requireExactSet": true,
      },
    },
    "passPredicateKey": "pass.act.core.masking.concept.variant-b",
  },
  "var.act.core.masking.math.a": {
    "variantId": "var.act.core.masking.math.a",
    "variantRevision": "1",
    "conceptFamily": "masking",
    "objectiveId": "obj.core.masking.math",
    "conceptTags": ["masking", "math"],
    "parentActivityId": "act.core.masking.math",
    "activityId": "act.core.masking.math.variant-a",
    "fixtureId": "fix.act.core.masking.math.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.masking.math variant a",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.core.masking.math.variant-a",
  },
  "var.act.core.masking.math.b": {
    "variantId": "var.act.core.masking.math.b",
    "variantRevision": "1",
    "conceptFamily": "masking",
    "objectiveId": "obj.core.masking.math",
    "conceptTags": ["masking", "math"],
    "parentActivityId": "act.core.masking.math",
    "activityId": "act.core.masking.math.variant-b",
    "fixtureId": "fix.act.core.masking.math.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.masking.math variant b",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.core.masking.math.variant-b",
  },
  "var.act.core.masking.impl.a": {
    "variantId": "var.act.core.masking.impl.a",
    "variantRevision": "1",
    "conceptFamily": "masking",
    "objectiveId": "obj.core.masking.impl",
    "conceptTags": ["masking", "implementation"],
    "parentActivityId": "act.core.masking.impl",
    "activityId": "act.core.masking.impl.variant-a",
    "fixtureId": "fix.act.core.masking.impl.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.masking.impl variant a",
    "evaluator": {
      "evaluatorId": "implementation.trace-match",
      "evaluatorRevision": "1",
      "params": {
        "expectedStepIds": ["s1", "s2"],
      },
    },
    "passPredicateKey": "pass.act.core.masking.impl.variant-a",
  },
  "var.act.core.masking.impl.b": {
    "variantId": "var.act.core.masking.impl.b",
    "variantRevision": "1",
    "conceptFamily": "masking",
    "objectiveId": "obj.core.masking.impl",
    "conceptTags": ["masking", "implementation"],
    "parentActivityId": "act.core.masking.impl",
    "activityId": "act.core.masking.impl.variant-b",
    "fixtureId": "fix.act.core.masking.impl.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.masking.impl variant b",
    "evaluator": {
      "evaluatorId": "implementation.trace-match",
      "evaluatorRevision": "1",
      "params": {
        "expectedStepIds": ["s1", "s2"],
      },
    },
    "passPredicateKey": "pass.act.core.masking.impl.variant-b",
  },
  "var.act.core.masking.explain.a": {
    "variantId": "var.act.core.masking.explain.a",
    "variantRevision": "1",
    "conceptFamily": "masking",
    "objectiveId": "obj.core.masking.concept",
    "conceptTags": ["masking", "explanation"],
    "parentActivityId": "act.core.masking.explain",
    "activityId": "act.core.masking.explain.variant-a",
    "fixtureId": "fix.act.core.masking.explain.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.core.masking.explain variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.core.masking.explain.variant-a",
  },
  "var.act.core.masking.explain.b": {
    "variantId": "var.act.core.masking.explain.b",
    "variantRevision": "1",
    "conceptFamily": "masking",
    "objectiveId": "obj.core.masking.concept",
    "conceptTags": ["masking", "explanation"],
    "parentActivityId": "act.core.masking.explain",
    "activityId": "act.core.masking.explain.variant-b",
    "fixtureId": "fix.act.core.masking.explain.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.masking.explain variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.core.masking.explain.variant-b",
  },
  "var.act.core.multi-head.concept.a": {
    "variantId": "var.act.core.multi-head.concept.a",
    "variantRevision": "1",
    "conceptFamily": "multi-head",
    "objectiveId": "obj.core.multi-head.concept",
    "conceptTags": ["multi-head", "concept"],
    "parentActivityId": "act.core.multi-head.concept",
    "activityId": "act.core.multi-head.concept.variant-a",
    "fixtureId": "fix.act.core.multi-head.concept.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.multi-head.concept variant a",
    "evaluator": {
      "evaluatorId": "concept.multiple-choice",
      "evaluatorRevision": "1",
      "params": {
        "correctOptionIds": ["correct"],
        "requireExactSet": true,
      },
    },
    "passPredicateKey": "pass.act.core.multi-head.concept.variant-a",
  },
  "var.act.core.multi-head.concept.b": {
    "variantId": "var.act.core.multi-head.concept.b",
    "variantRevision": "1",
    "conceptFamily": "multi-head",
    "objectiveId": "obj.core.multi-head.concept",
    "conceptTags": ["multi-head", "concept"],
    "parentActivityId": "act.core.multi-head.concept",
    "activityId": "act.core.multi-head.concept.variant-b",
    "fixtureId": "fix.act.core.multi-head.concept.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.multi-head.concept variant b",
    "evaluator": {
      "evaluatorId": "concept.multiple-choice",
      "evaluatorRevision": "1",
      "params": {
        "correctOptionIds": ["correct"],
        "requireExactSet": true,
      },
    },
    "passPredicateKey": "pass.act.core.multi-head.concept.variant-b",
  },
  "var.act.core.multi-head.math.a": {
    "variantId": "var.act.core.multi-head.math.a",
    "variantRevision": "1",
    "conceptFamily": "multi-head",
    "objectiveId": "obj.core.multi-head.math",
    "conceptTags": ["multi-head", "math"],
    "parentActivityId": "act.core.multi-head.math",
    "activityId": "act.core.multi-head.math.variant-a",
    "fixtureId": "fix.act.core.multi-head.math.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.multi-head.math variant a",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.core.multi-head.math.variant-a",
  },
  "var.act.core.multi-head.math.b": {
    "variantId": "var.act.core.multi-head.math.b",
    "variantRevision": "1",
    "conceptFamily": "multi-head",
    "objectiveId": "obj.core.multi-head.math",
    "conceptTags": ["multi-head", "math"],
    "parentActivityId": "act.core.multi-head.math",
    "activityId": "act.core.multi-head.math.variant-b",
    "fixtureId": "fix.act.core.multi-head.math.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.multi-head.math variant b",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.core.multi-head.math.variant-b",
  },
  "var.act.core.multi-head.impl.a": {
    "variantId": "var.act.core.multi-head.impl.a",
    "variantRevision": "1",
    "conceptFamily": "multi-head",
    "objectiveId": "obj.core.multi-head.impl",
    "conceptTags": ["multi-head", "implementation"],
    "parentActivityId": "act.core.multi-head.impl",
    "activityId": "act.core.multi-head.impl.variant-a",
    "fixtureId": "fix.act.core.multi-head.impl.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.multi-head.impl variant a",
    "evaluator": {
      "evaluatorId": "implementation.trace-match",
      "evaluatorRevision": "1",
      "params": {
        "expectedStepIds": ["s1", "s2"],
      },
    },
    "passPredicateKey": "pass.act.core.multi-head.impl.variant-a",
  },
  "var.act.core.multi-head.impl.b": {
    "variantId": "var.act.core.multi-head.impl.b",
    "variantRevision": "1",
    "conceptFamily": "multi-head",
    "objectiveId": "obj.core.multi-head.impl",
    "conceptTags": ["multi-head", "implementation"],
    "parentActivityId": "act.core.multi-head.impl",
    "activityId": "act.core.multi-head.impl.variant-b",
    "fixtureId": "fix.act.core.multi-head.impl.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.multi-head.impl variant b",
    "evaluator": {
      "evaluatorId": "implementation.trace-match",
      "evaluatorRevision": "1",
      "params": {
        "expectedStepIds": ["s1", "s2"],
      },
    },
    "passPredicateKey": "pass.act.core.multi-head.impl.variant-b",
  },
  "var.act.core.multi-head.explain.a": {
    "variantId": "var.act.core.multi-head.explain.a",
    "variantRevision": "1",
    "conceptFamily": "multi-head",
    "objectiveId": "obj.core.multi-head.concept",
    "conceptTags": ["multi-head", "explanation"],
    "parentActivityId": "act.core.multi-head.explain",
    "activityId": "act.core.multi-head.explain.variant-a",
    "fixtureId": "fix.act.core.multi-head.explain.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.core.multi-head.explain variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.core.multi-head.explain.variant-a",
  },
  "var.act.core.multi-head.explain.b": {
    "variantId": "var.act.core.multi-head.explain.b",
    "variantRevision": "1",
    "conceptFamily": "multi-head",
    "objectiveId": "obj.core.multi-head.concept",
    "conceptTags": ["multi-head", "explanation"],
    "parentActivityId": "act.core.multi-head.explain",
    "activityId": "act.core.multi-head.explain.variant-b",
    "fixtureId": "fix.act.core.multi-head.explain.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.multi-head.explain variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.core.multi-head.explain.variant-b",
  },
  "var.act.core.residual.concept.a": {
    "variantId": "var.act.core.residual.concept.a",
    "variantRevision": "1",
    "conceptFamily": "residual",
    "objectiveId": "obj.core.residual.concept",
    "conceptTags": ["residual", "concept"],
    "parentActivityId": "act.core.residual.concept",
    "activityId": "act.core.residual.concept.variant-a",
    "fixtureId": "fix.act.core.residual.concept.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.residual.concept variant a",
    "evaluator": {
      "evaluatorId": "concept.multiple-choice",
      "evaluatorRevision": "1",
      "params": {
        "correctOptionIds": ["correct"],
        "requireExactSet": true,
      },
    },
    "passPredicateKey": "pass.act.core.residual.concept.variant-a",
  },
  "var.act.core.residual.concept.b": {
    "variantId": "var.act.core.residual.concept.b",
    "variantRevision": "1",
    "conceptFamily": "residual",
    "objectiveId": "obj.core.residual.concept",
    "conceptTags": ["residual", "concept"],
    "parentActivityId": "act.core.residual.concept",
    "activityId": "act.core.residual.concept.variant-b",
    "fixtureId": "fix.act.core.residual.concept.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.residual.concept variant b",
    "evaluator": {
      "evaluatorId": "concept.multiple-choice",
      "evaluatorRevision": "1",
      "params": {
        "correctOptionIds": ["correct"],
        "requireExactSet": true,
      },
    },
    "passPredicateKey": "pass.act.core.residual.concept.variant-b",
  },
  "var.act.core.residual.math.a": {
    "variantId": "var.act.core.residual.math.a",
    "variantRevision": "1",
    "conceptFamily": "residual",
    "objectiveId": "obj.core.residual.math",
    "conceptTags": ["residual", "math"],
    "parentActivityId": "act.core.residual.math",
    "activityId": "act.core.residual.math.variant-a",
    "fixtureId": "fix.act.core.residual.math.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.residual.math variant a",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.core.residual.math.variant-a",
  },
  "var.act.core.residual.math.b": {
    "variantId": "var.act.core.residual.math.b",
    "variantRevision": "1",
    "conceptFamily": "residual",
    "objectiveId": "obj.core.residual.math",
    "conceptTags": ["residual", "math"],
    "parentActivityId": "act.core.residual.math",
    "activityId": "act.core.residual.math.variant-b",
    "fixtureId": "fix.act.core.residual.math.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.residual.math variant b",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.core.residual.math.variant-b",
  },
  "var.act.core.residual.impl.a": {
    "variantId": "var.act.core.residual.impl.a",
    "variantRevision": "1",
    "conceptFamily": "residual",
    "objectiveId": "obj.core.residual.impl",
    "conceptTags": ["residual", "implementation"],
    "parentActivityId": "act.core.residual.impl",
    "activityId": "act.core.residual.impl.variant-a",
    "fixtureId": "fix.act.core.residual.impl.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.residual.impl variant a",
    "evaluator": {
      "evaluatorId": "implementation.trace-match",
      "evaluatorRevision": "1",
      "params": {
        "expectedStepIds": ["s1", "s2"],
      },
    },
    "passPredicateKey": "pass.act.core.residual.impl.variant-a",
  },
  "var.act.core.residual.impl.b": {
    "variantId": "var.act.core.residual.impl.b",
    "variantRevision": "1",
    "conceptFamily": "residual",
    "objectiveId": "obj.core.residual.impl",
    "conceptTags": ["residual", "implementation"],
    "parentActivityId": "act.core.residual.impl",
    "activityId": "act.core.residual.impl.variant-b",
    "fixtureId": "fix.act.core.residual.impl.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.residual.impl variant b",
    "evaluator": {
      "evaluatorId": "implementation.trace-match",
      "evaluatorRevision": "1",
      "params": {
        "expectedStepIds": ["s1", "s2"],
      },
    },
    "passPredicateKey": "pass.act.core.residual.impl.variant-b",
  },
  "var.act.core.residual.explain.a": {
    "variantId": "var.act.core.residual.explain.a",
    "variantRevision": "1",
    "conceptFamily": "residual",
    "objectiveId": "obj.core.residual.concept",
    "conceptTags": ["residual", "explanation"],
    "parentActivityId": "act.core.residual.explain",
    "activityId": "act.core.residual.explain.variant-a",
    "fixtureId": "fix.act.core.residual.explain.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.core.residual.explain variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.core.residual.explain.variant-a",
  },
  "var.act.core.residual.explain.b": {
    "variantId": "var.act.core.residual.explain.b",
    "variantRevision": "1",
    "conceptFamily": "residual",
    "objectiveId": "obj.core.residual.concept",
    "conceptTags": ["residual", "explanation"],
    "parentActivityId": "act.core.residual.explain",
    "activityId": "act.core.residual.explain.variant-b",
    "fixtureId": "fix.act.core.residual.explain.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.residual.explain variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.core.residual.explain.variant-b",
  },
  "var.act.core.encdec.concept.a": {
    "variantId": "var.act.core.encdec.concept.a",
    "variantRevision": "1",
    "conceptFamily": "encdec",
    "objectiveId": "obj.core.encdec.concept",
    "conceptTags": ["encdec", "concept"],
    "parentActivityId": "act.core.encdec.concept",
    "activityId": "act.core.encdec.concept.variant-a",
    "fixtureId": "fix.act.core.encdec.concept.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.encdec.concept variant a",
    "evaluator": {
      "evaluatorId": "concept.multiple-choice",
      "evaluatorRevision": "1",
      "params": {
        "correctOptionIds": ["correct"],
        "requireExactSet": true,
      },
    },
    "passPredicateKey": "pass.act.core.encdec.concept.variant-a",
  },
  "var.act.core.encdec.concept.b": {
    "variantId": "var.act.core.encdec.concept.b",
    "variantRevision": "1",
    "conceptFamily": "encdec",
    "objectiveId": "obj.core.encdec.concept",
    "conceptTags": ["encdec", "concept"],
    "parentActivityId": "act.core.encdec.concept",
    "activityId": "act.core.encdec.concept.variant-b",
    "fixtureId": "fix.act.core.encdec.concept.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.encdec.concept variant b",
    "evaluator": {
      "evaluatorId": "concept.multiple-choice",
      "evaluatorRevision": "1",
      "params": {
        "correctOptionIds": ["correct"],
        "requireExactSet": true,
      },
    },
    "passPredicateKey": "pass.act.core.encdec.concept.variant-b",
  },
  "var.act.core.encdec.math.a": {
    "variantId": "var.act.core.encdec.math.a",
    "variantRevision": "1",
    "conceptFamily": "encdec",
    "objectiveId": "obj.core.encdec.math",
    "conceptTags": ["encdec", "math"],
    "parentActivityId": "act.core.encdec.math",
    "activityId": "act.core.encdec.math.variant-a",
    "fixtureId": "fix.act.core.encdec.math.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.encdec.math variant a",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.core.encdec.math.variant-a",
  },
  "var.act.core.encdec.math.b": {
    "variantId": "var.act.core.encdec.math.b",
    "variantRevision": "1",
    "conceptFamily": "encdec",
    "objectiveId": "obj.core.encdec.math",
    "conceptTags": ["encdec", "math"],
    "parentActivityId": "act.core.encdec.math",
    "activityId": "act.core.encdec.math.variant-b",
    "fixtureId": "fix.act.core.encdec.math.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.encdec.math variant b",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.core.encdec.math.variant-b",
  },
  "var.act.core.encdec.impl.a": {
    "variantId": "var.act.core.encdec.impl.a",
    "variantRevision": "1",
    "conceptFamily": "encdec",
    "objectiveId": "obj.core.encdec.impl",
    "conceptTags": ["encdec", "implementation"],
    "parentActivityId": "act.core.encdec.impl",
    "activityId": "act.core.encdec.impl.variant-a",
    "fixtureId": "fix.act.core.encdec.impl.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.encdec.impl variant a",
    "evaluator": {
      "evaluatorId": "implementation.trace-match",
      "evaluatorRevision": "1",
      "params": {
        "expectedStepIds": ["s1", "s2"],
      },
    },
    "passPredicateKey": "pass.act.core.encdec.impl.variant-a",
  },
  "var.act.core.encdec.impl.b": {
    "variantId": "var.act.core.encdec.impl.b",
    "variantRevision": "1",
    "conceptFamily": "encdec",
    "objectiveId": "obj.core.encdec.impl",
    "conceptTags": ["encdec", "implementation"],
    "parentActivityId": "act.core.encdec.impl",
    "activityId": "act.core.encdec.impl.variant-b",
    "fixtureId": "fix.act.core.encdec.impl.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.encdec.impl variant b",
    "evaluator": {
      "evaluatorId": "implementation.trace-match",
      "evaluatorRevision": "1",
      "params": {
        "expectedStepIds": ["s1", "s2"],
      },
    },
    "passPredicateKey": "pass.act.core.encdec.impl.variant-b",
  },
  "var.act.core.encdec.explain.a": {
    "variantId": "var.act.core.encdec.explain.a",
    "variantRevision": "1",
    "conceptFamily": "encdec",
    "objectiveId": "obj.core.encdec.concept",
    "conceptTags": ["encdec", "explanation"],
    "parentActivityId": "act.core.encdec.explain",
    "activityId": "act.core.encdec.explain.variant-a",
    "fixtureId": "fix.act.core.encdec.explain.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.core.encdec.explain variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.core.encdec.explain.variant-a",
  },
  "var.act.core.encdec.explain.b": {
    "variantId": "var.act.core.encdec.explain.b",
    "variantRevision": "1",
    "conceptFamily": "encdec",
    "objectiveId": "obj.core.encdec.concept",
    "conceptTags": ["encdec", "explanation"],
    "parentActivityId": "act.core.encdec.explain",
    "activityId": "act.core.encdec.explain.variant-b",
    "fixtureId": "fix.act.core.encdec.explain.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.encdec.explain variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.core.encdec.explain.variant-b",
  },
  "var.act.core.autoregressive.concept.a": {
    "variantId": "var.act.core.autoregressive.concept.a",
    "variantRevision": "1",
    "conceptFamily": "autoregressive",
    "objectiveId": "obj.core.autoregressive.concept",
    "conceptTags": ["autoregressive", "concept"],
    "parentActivityId": "act.core.autoregressive.concept",
    "activityId": "act.core.autoregressive.concept.variant-a",
    "fixtureId": "fix.act.core.autoregressive.concept.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.autoregressive.concept variant a",
    "evaluator": {
      "evaluatorId": "concept.multiple-choice",
      "evaluatorRevision": "1",
      "params": {
        "correctOptionIds": ["correct"],
        "requireExactSet": true,
      },
    },
    "passPredicateKey": "pass.act.core.autoregressive.concept.variant-a",
  },
  "var.act.core.autoregressive.concept.b": {
    "variantId": "var.act.core.autoregressive.concept.b",
    "variantRevision": "1",
    "conceptFamily": "autoregressive",
    "objectiveId": "obj.core.autoregressive.concept",
    "conceptTags": ["autoregressive", "concept"],
    "parentActivityId": "act.core.autoregressive.concept",
    "activityId": "act.core.autoregressive.concept.variant-b",
    "fixtureId": "fix.act.core.autoregressive.concept.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.autoregressive.concept variant b",
    "evaluator": {
      "evaluatorId": "concept.multiple-choice",
      "evaluatorRevision": "1",
      "params": {
        "correctOptionIds": ["correct"],
        "requireExactSet": true,
      },
    },
    "passPredicateKey": "pass.act.core.autoregressive.concept.variant-b",
  },
  "var.act.core.autoregressive.math.a": {
    "variantId": "var.act.core.autoregressive.math.a",
    "variantRevision": "1",
    "conceptFamily": "autoregressive",
    "objectiveId": "obj.core.autoregressive.math",
    "conceptTags": ["autoregressive", "math"],
    "parentActivityId": "act.core.autoregressive.math",
    "activityId": "act.core.autoregressive.math.variant-a",
    "fixtureId": "fix.act.core.autoregressive.math.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.autoregressive.math variant a",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.core.autoregressive.math.variant-a",
  },
  "var.act.core.autoregressive.math.b": {
    "variantId": "var.act.core.autoregressive.math.b",
    "variantRevision": "1",
    "conceptFamily": "autoregressive",
    "objectiveId": "obj.core.autoregressive.math",
    "conceptTags": ["autoregressive", "math"],
    "parentActivityId": "act.core.autoregressive.math",
    "activityId": "act.core.autoregressive.math.variant-b",
    "fixtureId": "fix.act.core.autoregressive.math.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.autoregressive.math variant b",
    "evaluator": {
      "evaluatorId": "concept.exact-numeric",
      "evaluatorRevision": "1",
      "params": {
        "expected": 1,
        "tolerance": 0,
      },
    },
    "passPredicateKey": "pass.act.core.autoregressive.math.variant-b",
  },
  "var.act.core.autoregressive.impl.a": {
    "variantId": "var.act.core.autoregressive.impl.a",
    "variantRevision": "1",
    "conceptFamily": "autoregressive",
    "objectiveId": "obj.core.autoregressive.impl",
    "conceptTags": ["autoregressive", "implementation"],
    "parentActivityId": "act.core.autoregressive.impl",
    "activityId": "act.core.autoregressive.impl.variant-a",
    "fixtureId": "fix.act.core.autoregressive.impl.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.autoregressive.impl variant a",
    "evaluator": {
      "evaluatorId": "implementation.trace-match",
      "evaluatorRevision": "1",
      "params": {
        "expectedStepIds": ["s1", "s2"],
      },
    },
    "passPredicateKey": "pass.act.core.autoregressive.impl.variant-a",
  },
  "var.act.core.autoregressive.impl.b": {
    "variantId": "var.act.core.autoregressive.impl.b",
    "variantRevision": "1",
    "conceptFamily": "autoregressive",
    "objectiveId": "obj.core.autoregressive.impl",
    "conceptTags": ["autoregressive", "implementation"],
    "parentActivityId": "act.core.autoregressive.impl",
    "activityId": "act.core.autoregressive.impl.variant-b",
    "fixtureId": "fix.act.core.autoregressive.impl.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "form-sequence",
    "estimatedMinutes": 8,
    "title": "act.core.autoregressive.impl variant b",
    "evaluator": {
      "evaluatorId": "implementation.trace-match",
      "evaluatorRevision": "1",
      "params": {
        "expectedStepIds": ["s1", "s2"],
      },
    },
    "passPredicateKey": "pass.act.core.autoregressive.impl.variant-b",
  },
  "var.act.core.autoregressive.explain.a": {
    "variantId": "var.act.core.autoregressive.explain.a",
    "variantRevision": "1",
    "conceptFamily": "autoregressive",
    "objectiveId": "obj.core.autoregressive.concept",
    "conceptTags": ["autoregressive", "explanation"],
    "parentActivityId": "act.core.autoregressive.explain",
    "activityId": "act.core.autoregressive.explain.variant-a",
    "fixtureId": "fix.act.core.autoregressive.explain.variant-a",
    "fixtureRevision": "1",
    "surfaceFormFamily": "multiple-choice",
    "estimatedMinutes": 8,
    "title": "act.core.autoregressive.explain variant a",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.core.autoregressive.explain.variant-a",
  },
  "var.act.core.autoregressive.explain.b": {
    "variantId": "var.act.core.autoregressive.explain.b",
    "variantRevision": "1",
    "conceptFamily": "autoregressive",
    "objectiveId": "obj.core.autoregressive.concept",
    "conceptTags": ["autoregressive", "explanation"],
    "parentActivityId": "act.core.autoregressive.explain",
    "activityId": "act.core.autoregressive.explain.variant-b",
    "fixtureId": "fix.act.core.autoregressive.explain.variant-b",
    "fixtureRevision": "1",
    "surfaceFormFamily": "labeled-table",
    "estimatedMinutes": 8,
    "title": "act.core.autoregressive.explain variant b",
    "evaluator": {
      "evaluatorId": "explanation.structured-rubric",
      "evaluatorRevision": "1",
      "params": {
        "requiredFields": ["claim", "evidence"],
        "minimumNonEmpty": 2,
      },
    },
    "passPredicateKey": "pass.act.core.autoregressive.explain.variant-b",
  },
});

export const VARIANTS: Readonly<Record<string, VariantDefinition>> = VARIANTS_DATA as unknown as Readonly<Record<string, VariantDefinition>>;
